### ISSUE TITLE
Zcoin sync error due to hardfork.

### ISSUE THREAD

**Issue by etkim7** [firoorg/firo#1002]
Below is still not solved. As it is closed, I write one more issue now.
https://github.com/firoorg/firo/issues/975

It constantly stuck.
It syncs well with empty wallet.dat but it stuck with normal worked wallet.dat
I tried
- sync from scratch (no blockchain, no wallet.dat) -> synced well -> changed wallet.dat to old -> reindex -> synced to wrong chain.
- sync from scratch (no blockchain, no wallet.dat) -> synced well -> changed wallet.dat to old -> rescan -> stuck at 345959
seems like 345959 is where I tried rescan.
wallet.dat itself seems corrupted or firo sync is broken when there's wrong blockchain data in the wallet.dat

`-allowdeepreorg` doesn't help. tried reconsiderblock but the wallet just hangs.

**Comment by justanwar** [comment]
Are you on v0.14.5.2? Have you tried starting QT with `-zapwallettxes` with the old wallet.dat?

**Comment by etkim7** [comment]
yes trying from 0.14.5.2. zapwallettxes just flushes wallet.dat
seems like it is corrupted. Usually it is fixed when we synced from scratch but sync is not working as expected.
Why not add checkpoint to add forced block to every node? As firo hardforked quite frequently these days, few nodes are still running in the old state.

**Comment by justanwar** [comment]
Could you try with v0.14.5.3? How old is your wallet?

**Comment by etkim7** [comment]
I tried it again with v0.14.5.3 but no luck.
I used wallet.dat just before the hardfork time. It's not old.

Recovered from backup wallet.dat and now it's synced well.
Please do not hardfork too frequently. wallet.dat is the pain point of bitcoin type coins. It's hard to manage, affects sync can be corrupted easily.

**Comment by xixou2** [comment]
I have the same issue.
I had an old Zcoin wallet and Firo couldn't sync the last 3 weeks.
So I created a new firo wallet and transfert from my Zcoin wallet to my new firo wallet and that was ok.
I can now fully sync the firo wallet.
