### ISSUE TITLE
Anonymize All does not work if you have firo nodes.

### ISSUE THREAD

**Issue by vodkadrunkinski** [firoorg/firo#1005]
### Describe the issue
Clicking on Anonymize All when you can part of your funds locked in firo nodes gives one of two errors:
"Unable to generate mint: Blockchain not yet synced."
or
"Fail to mint all public balance, Insufficient funds"

### Can you reliably reproduce the issue?
Happens every time.

#### If so, please list the steps to reproduce below:
1. Using latest v.0.14.5.3 release
2. Have some firo nodes.  Make sure there's some Firo that's NOT locked in Firo nodes and anonymizable.
3. Click on "Anonymize all"

### Expected behaviour
Anonymize unlocked balance.

### Actual behaviour
Cannot anonymize anything.

### Screenshots.
Screenshots attached.

### Machine specs:
- OS: Win64
- CPU: Ryzen 5950x
- RAM: 32GB
- Disk size: 2TB
- Disk Type (HD/SDD): NVME

![image](https://user-images.githubusercontent.com/6166556/108662637-ba8eac80-7509-11eb-9037-5f0839cb6e41.png)
![image](https://user-images.githubusercontent.com/6166556/108662722-e01bb600-7509-11eb-802e-0c23c861e49f.png)

**Comment by azilber** [comment]
Doing a mintlelantus works from the console.  Just not "Anonymize all" it seems...

**Comment by vodkadrunkinski** [comment]
I restored an old wallet.dat and resynced.  Now it works.
