### ISSUE TITLE
Add warning that Lelantus spend shoud not be made to Trezor controlled address directly

### ISSUE THREAD

**Issue by yura-pakhuchiy** [firoorg/firo#1027]
See https://github.com/trezor/trezor-firmware/issues/1588
If user wants send funds to Trezor, they should spend to software wallet first and then send to Trezor.

**Comment by hakonamatata** [comment]
Just to be clear, does this mean

1. Open Firo Core wallet
2. Anonymize coins
3. Create a new address in the same Firo Core wallet
4. Send anonymized coins to new address 
5. Then send regular transparent balance to Trezor

Essentially, only use "transparent balance", when sending to Trezor?

**Comment by yura-pakhuchiy** [comment]
@hakonamatata correct

**Comment by reubenyap** [comment]
This is now resolved by #1063 and has now been merged and released with the latest Trezor firmware https://github.com/trezor/trezor-firmware/issues/1767

Many thanks for all the assistance @yura-pakhuchiy
