### ISSUE TITLE
Reduce scriptSig length for Lelantus transactions

### ISSUE THREAD

**Issue by yura-pakhuchiy** [firoorg/firo#1028]
See https://github.com/trezor/trezor-firmware/issues/1588
Long scriptSig prevents Trezor from signing transactions which uses Lelantus spends as inputs. However Trezor supports long transaction data if it placed after the transaction (similar to Firo coinbase transactions and Zcash privacy transactions). Firo can move Lelantus data from scriptSig to the end of transaction in the next hard fork. Without this change Trezor probably will remove Firo support.

**Comment by yura-pakhuchiy** [comment]
@reubenyap @levonpetrosyan93 @nopslide consider implementing this ASAP to avoid removal of Trezor support

**Comment by psolstice** [comment]
As a solution we will move most of the data for lelantus mint/joinspits into transaction v3 payload field (`CTransaction::vExtraPayload`). This is a field introduced in DASH for proreg data and it should be compatible with hardware wallets. This will make `scriptSig` compatible with Trezor.

**Comment by reubenyap** [comment]
This is resolved with #1063
