### ISSUE TITLE
Random core dump file on firo node

### ISSUE THREAD

**Issue by NorseGaud** [firoorg/firo#1035]
### Describe the issue

Found a random core dump file on my node. I can't gdb it as I don't have ubuntu.

```
Core was generated by `/bin/firod -printtoconsole'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007fb2fefd95df in ?? ()
[Current thread is 1 (LWP 13)]
```
### Can you reliably reproduce the issue?
no

### Machine specs:
Amazon Linux 2 (using official firo dockerhub image though, which is ubuntu)
t3a.micro

FIRO: 0.14.6.0

At the time of the core dump, CPU spiked, but not really higher than usual spikes:

![Screen Shot 2021-05-15 at 11 57 00 PM](https://user-images.githubusercontent.com/5896030/118385027-6ca1b600-b5d9-11eb-8d37-5fc979defb95.png)

Download link for the archived core: https://mega.nz/file/WhVXUYpD#CCLJ9sn8SQq5bP3l3bH87xdZKNO1s7m_vrLDd-tAVfs

**Comment by reubenyap** [comment]
The next release has some crash fixes so let's see if it works to resolve this.

**Comment by reubenyap** [comment]
Re-open if still an issue.
