### ISSUE TITLE
firo node testnet not syn after block 35000

### ISSUE THREAD

**Issue by 0xkongamoto** [firoorg/firo#1057]
firo release versioin 14.07.01

i started node testnet, but node is not continue after block 3500

rpc -> getinfo
{
    "result": {
        "version": 140701,
        "protocolversion": 90030,
        "walletversion": 130000,
        "balance": 0.00000000,
        "blocks": 35000,
        "timeoffset": 0,
        "connections": 8,
        "proxy": "",
        "difficulty": 5.960464477539062e-08,
        "testnet": true,
        "keypoololdest": 1627367514,
        "keypoolsize": 100,
        "paytxfee": 0.00000000,
        "mininput": 0.00001000,
        "relayfee": 0.00001000,
        "errors": ""
    },
    "error": null,
    "id": "1"
}

**Comment by reubenyap** [comment]
Hello! We are internally testing some hard fork stuff so we upgraded our testnet so it won't work. Hang tight we'll be releasing the code soon. Did you need any assistance in particular?

**Comment by reubenyap** [comment]
Let me know if this issue still persists after using the latest master. Closing this for now.
