### ISSUE TITLE
InstantSend dropdown menu in Transaction list no longer showing text

### ISSUE THREAD

**Issue by justanwar** [firoorg/firo#1087]
Was working before QT reskin.

![qt-reskin-is-dropdown](https://user-images.githubusercontent.com/42809091/142587479-13450af4-8327-4318-bfe6-315e97aa479b.png)

**Comment by a-bezrukov** [comment]
It was not on Windows
![image](https://user-images.githubusercontent.com/36845392/142600777-f6eaf90a-f29c-44da-a4e4-e42b53f58e51.png)

**Comment by justanwar** [comment]
Is there a minimum width before the `...` shows up? This was on the pre-release binaries: https://github.com/firoorg/firo/releases/tag/v0.14.9.2

**Comment by a-bezrukov** [comment]
Yes, the `...` is shown when the DropDown box is too narrow. Windows controls this behavior. It's OK on Linux

**Comment by a-bezrukov** [comment]
Macos is OK too
