### ISSUE TITLE
Notification icon on macOS is bitcoin

### ISSUE THREAD

**Issue by KuroGuo** [firoorg/firo#1094]
### Description

Notification icon on macOS is bitcoin

### Steps to reproduce

1. Switch to the Send tab
2. Send a transaction

### Screenshot

![image](https://user-images.githubusercontent.com/8684548/145126078-292afcf9-f219-4383-9de8-6895c5515421.png)

### Firo version

Firo v0.14.9.1

### Machine specs

- OS: macOS Monterey

**Comment by justanwar** [comment]
Could you check if this issue is still present in v0.14.9.2?

**Comment by KuroGuo** [comment]
I checked, same issue in v0.14.9.2

**Comment by justanwar** [comment]
![image](https://user-images.githubusercontent.com/42809091/146688152-3d75be1d-7cfc-45be-a72d-dd21b13ff903.png)

Is it on this screen?

**Comment by KuroGuo** [comment]
Yes. And I found that I also had the Bitcoin Core wallet installed on my MacBook. After I uninstalled Bitcoin Core, I didn't have this issue anymore and the icon reverted to Firo icon.

I guess the cause of this issue may be that the notification function is called with the name of Bitcoin, or the name of Bitcoin somewhere in the code.

However, I installed Bitcore Core again and tried to reproduce it but could not reproduce it again.

**Comment by KuroGuo** [comment]
I successfully reproduced it.

## Steps to reproduce

1. Install Bitcoin Core
2. Enable Bitcoin Core Notifacations in System Settings
2. Disable Firo Core Notifacations in System Settings
3. Open Firo Core
4. Switch to the Send tab
5. Send a transaction
