### ISSUE TITLE
v0.14.9.2, Transactions page width keeps growing

### ISSUE THREAD

**Issue by KuroGuo** [firoorg/firo#1099]
### Description

v0.14.9.2, Transactions page width keeps growing

### Steps to reproduce

1. Switch to the Transactions tab

### Screenshot

https://user-images.githubusercontent.com/8684548/146629264-565f6c4d-7370-4297-88ce-456ee9a9527a.mp4

### Firo version

Firo v0.14.9.2

### Machine specs

- OS: macOS Monterey

**Comment by levonpetrosyan93** [comment]
Fixed in #1111
