### ISSUE TITLE
Minimum height of QT wallet is greater than my screen

### ISSUE THREAD

**Issue by xorzero777** [firoorg/firo#1112]
_**Minimum height of QT wallet is greater than my screen and resize cannot reduce. Also there is no full screen view. Maybe consider putting sliders on the side of each tab?**_

![image](https://user-images.githubusercontent.com/42816019/147263522-16df880c-8852-4012-9434-dcfb4f63c4a6.png)

- v0.14.9.2-g738308bfc

- OS: Ubuntu 20.04 (Gnome)

**Comment by KuroGuo** [comment]
I think the font size in css is too big

**Comment by xorzero777** [comment]
Does QT graphics use CSS?

**Comment by KuroGuo** [comment]
> Does QT graphics use CSS?

Yes. https://github.com/firoorg/firo/blob/master/src/qt/res/css/firo.css#L15

**Comment by xorzero777** [comment]
Ok new style QT .. I wrote/used QT before but the old style.

**Comment by xorzero777** [comment]
Ok so how do I fix my Issue ...

**Comment by KuroGuo** [comment]
> Ok so how do I fix my Issue ...

Wait for the developers to fix it

**Comment by xorzero777** [comment]
Ok .. thanks for clarification ;-)

**Comment by KuroGuo** [comment]
I found that the font size in [css](https://github.com/firoorg/firo/commits/master/src/qt/res/css/firo.css) was changed twice, the two developers seem to be unaware of each other, maybe 10pt is more appropriate.

![2c5259d499e8a342a61d62e507040ea](https://user-images.githubusercontent.com/8684548/150287513-cb97419e-e06c-4fb0-ad0b-280b00927dff.png)

**Comment by WonderLand33** [comment]
same to me

**Comment by justanwar** [comment]
Fixed in #1152

**Comment by xorzero777** [comment]
![image](https://user-images.githubusercontent.com/42816019/163557836-101745d8-eaec-4f0e-996b-7c5324889b73.png)
For me this showed in 0.14.9.5 ... 

OS: Ubuntu 20.04 (Gnome)
v0.14.9.5-gb764c08df

Although I cannot see the lowest extent of the window .. this is now usable so thanks and no complaint ;-)

**Comment by levonpetrosyan93** [comment]
> ![image](https://user-images.githubusercontent.com/42816019/163557836-101745d8-eaec-4f0e-996b-7c5324889b73.png) For me this showed in 0.14.9.5 ...
> 
> OS: Ubuntu 20.04 (Gnome) v0.14.9.5-gb764c08df
> 
> Although I cannot see the lowest extent of the window .. this is now usable so thanks and no complaint ;-)

Could you please tell your screen resolution?

**Comment by xorzero777** [comment]
![image](https://user-images.githubusercontent.com/42816019/163564421-e6af65b7-2a08-4495-ab28-600df5bafaff.png)
