### ISSUE TITLE
Cannot be minimized to tray

### ISSUE THREAD

**Issue by KuroGuo** [firoorg/firo#1139]
Cannot be minimized to tray

### Screenshot

https://user-images.githubusercontent.com/8684548/154405540-18cdde80-4ef1-4f87-9b02-a370b11a7aa4.mp4

### Firo version

v0.14.9.4

### Machine specs

- OS: Windows 11

**Comment by justanwar** [comment]
Able to minimize to tray if using the Minimize button and "Minimized to the tray instead of the taskbar" is enabled in Options.

Does not work with Show/Hide.

OS: Windows 10

**Comment by justanwar** [comment]
Fixed in #1154
