### ISSUE TITLE
Stress Test for Raspberry Pi

### ISSUE THREAD

**Issue by fanaticalfishing** [firoorg/firo#1160]
Reuben asked how the Raspberry Pi performs when receiving a Lelantus block. I anonymized a few Firo in firo-qt and monitored the
Pi running firod. Below is the pastebin with the result. The pi has 4 processors and 8gb ram. Is there a script that I could use to
send multiple Lelantus transactions on testnet to give the pi a stress test?

https://pastebin.com/nZGV5SLs

**Comment by justanwar** [comment]
This counts as one transaction:
`joinsplit "{\"address01\":1,\"address02\":1}"`

Repeat as necessary.

**Comment by fanaticalfishing** [comment]
Thank you. So far firod on testnet doesn't register as much as a blip when multiple lelantus transactions are received. ill experiment more

**Comment by fanaticalfishing** [comment]
I fed the PI thousands of lelantus transactions from two computers simultaneously. There was very little load.
 A small part of the log of the system load is in the pastebin below. It is clear to me that as of now, the Pi can handle anything that firod can throw at it. If you want to test something else on the Pi. Let me know. If not, we can close this issue.
https://pastebin.com/TcVQ7C4A

**Comment by justanwar** [comment]
Thank you for testing! You can close this issue.
