### ISSUE TITLE
[enhancement] Firo Paper Wallet

### ISSUE THREAD

**Issue by expatjedi** [firoorg/firo#1169]
Hello. I have created an open-source paper wallet generator for Firo. It creates addresses and private keys in compressed format. If you have a look and add into your website, it will be much appreciated. This generator designed to work as offline. Please use it freely after reading the instructions carefully.

Website: https://holdmywallet.com/

Firo: https://holdmywallet.com/firo.html

Source Code: https://github.com/koraycoding/paper-wallet

**Comment by skironDotNet** [comment]
I think nothing beats that tool
https://iancoleman.io/bip39/

**Comment by reubenyap** [comment]
hi thanks @expatjedi ! Just wondering because the default wallet doesn't allow importing private keys unless you disable HD mode which is not how we recommend to use the wallet. But we do see some calls for it.

**Comment by skironDotNet** [comment]
I think wallet should allow import of private keys with HD enabled.
Other crypto does it. Basically when you export wallet it export all HD keys with their path like 44'/0/1 (whatever the format is) and then export all imported non HD created keys

**Comment by erciccione** [comment]
Website doesn't exist anymore. I suggest to close this issue.
