### ISSUE TITLE
[BUG] RAP address will lose funds!!!

### ISSUE THREAD

**Issue by skironDotNet** [firoorg/firo#1178]
Test scenario to reproduce:
1. Create 2 HD wallets with different recovery words (both created with `-usemenmonic -usehd=1 -mnemonic="words here"`) 
  - NOTE: `-usemenmonic` without `-usehd=1` so `-usemenmonic -usehd=0`  would ignore mnemonic and you are ducked - that's different bug
2. Let's call first wallet with private funds (Lelantus) available the Sender wallet
3. Let's call second empty wallet the Receiver wallet
4. Generate RAP address in Receiver 
5. In Sender wallet go to Send tab private balance (_I'm not sure if bug is for only private or both I'm assuming both but tested with private_) enter RAP address obtained in Receiver and click send funds.
6. The Sender wallet will now ask to link RAP address you confirm ok, this will take 0.00013897 from your Sender balance, and send it to Receiver (the exact amount after 0.0001 will differ by fee I'm assuming)
7. Receiver will recognize 1st RAP transaction and show up in the transactions tab as received 0.0001, but the receiving address is not bip39, so I don't know if restoring wallet via `-usemenmonic` will actually include that transaction in resored wallet (WARNING 1)
8. So now Sender and Receiver is linked via RAP, and **NOW FUN BEGINS**
9. Send another amount from Sender to the same RAP address, your Sender wallet will show you new destination transparent address, click ok.
10. Poof, **Receiver will newer receive it** the new address generated by RAP derivation is not part of the Receiver wallet, you can never recover the funds, unless it's a bug in QT and possible to fix RAP derivation and rescan your wallet in the future.

As of right now Sender wallet will show you 2 RAP transactions (using scenario above) so 1st is linking tx, and 2nd is an actual fee less transaction of fund. You can access TX ID of both transactions in Sender wallet and verify on the blockchain explorer but Receiver has no awareness of 2ns transaction, so I'm assuming RAP generated 2nd address but now is not included in Receiver wallet.

If this is not a bug then how can I see received funds by RAP address? I'm so glad I was cautious and send only 0.1 test transaction using real funds. From now on I will play with "features" only on the test net.

**Comment by justanwar** [comment]
The number of RAP addresses to be generated can be selected at wallet restoration (if using UI). The equivalent option is `-defaultpcodenumber=x` where x is the number of RAP addresses to be generated.

**Comment by justanwar** [comment]
The quote is "sender can derive new addresses without receiver's input" which is different than the current situation which is "receiver is restoring funds from RAP addresses."

You will need to restore the Receiver wallet with the following command-line options:
`-usemnemonic -mnemonic="words here" -defaultpcodenumber=x`
where x is the number of RAP addresses you have generated before plus some more just in case.

**Comment by skironDotNet** [comment]
Finally had a chance to test it. It does work. Yey, but very cryptic, aka no documentation for this. Now this ticket is the documentation, Thank you.
