### ISSUE TITLE
v0.14.11.1-g1e9bad81f Firo Core Wallet stuck sync

### ISSUE THREAD

**Issue by CyrilleHulin** [firoorg/firo#1201]
Hello,
I'm actually meeting a pb of Sync my Firo Wallet.
![image](https://user-images.githubusercontent.com/49069375/183241567-665e79a6-0570-481c-8a53-e8ac15b2bee6.png)

Do you have any idea?

Cyrille

**Comment by justanwar** [comment]
Please backup your wallet.dat and perform the following steps:

0. Ensure the wallet is not running.
1. Navigate to the [Firo data directory.](https://github.com/firoorg/firo/wiki/Default-data-directories)
2. Delete the following folders:
```
blocks
chainstate
llmq
evodb
```
3. Start the wallet again. It will start syncing from scratch and once complete, you should be able to use your wallet.

**Comment by CyrilleHulin** [comment]
I'm doing it.
We stay connected to know the result.
Cyrille

**Comment by justanwar** [comment]
Please let us know the results of the troubleshooting steps.

**Comment by CyrilleHulin** [comment]
Worked perfectly.
Thank you for your help @justanwar
