### ISSUE TITLE
firo.conf

### ISSUE THREAD

**Issue by yanuvelir** [firoorg/firo#1221]
Please tell me what configuration needs to be entered in the file so that the node can be synchronized

**Comment by justanwar** [comment]
The node can be synchronized without having a firo.conf. What problem are you facing?

**Comment by yanuvelir** [comment]
2022-12-23 12:42:54 CMasternodeSync::ProcessTick -- nTick 255068 nCurrentAsset 0 nTriedPeerCount 0 nSyncProgress -0.250000
2022-12-23 12:42:54 After closing Dandelion connections:
  vDandelionInbound: 
  vDandelionOutbound: 
  vDandelionDestination: 
  mDandelionRoutes: 
  localDandelionDestination: nullptr
2022-12-23 12:42:55 After closing Dandelion connections:


doesn't want to sync
what should be written in the .conf file to start synchronization?

**Comment by yanuvelir** [comment]
my file says rpcallowip
rpcbind
rpcuser
Maybe some other settings are missing?

**Comment by justanwar** [comment]
Please check if you are connected to any peers at all with either `./firo-cli getinfo` or `./firo-cli getpeerinfo`. Also check if your firewall allows connections through port 8168.
