### ISSUE TITLE
masternode not showed as mine in firo client

### ISSUE THREAD

**Issue by smash-necros** [firoorg/firo#1222]
Hi
I've just registered masternode
I can see it in All masternodes
node status is Ready
collateral is locked in my firo client 
owneraddress is one of my recieve adressess, not collateral not fee and so on... it's the first one that was created by wallet

why client says that I don't have any masternodes?

**Comment by justanwar** [comment]
1. On which page or tab were you unable to see your masternode?
2. Is the `My masternodes only` box checked?

**Comment by smash-necros** [comment]
![image](https://user-images.githubusercontent.com/49901481/210576292-88e7f098-cc84-4c24-9969-4205a13488ff.png)
