### ISSUE TITLE
Dockerfile needs updating

### ISSUE THREAD

**Issue by skironDotNet** [firoorg/firo#1223]
code `zlib-1.2.11` must be changed to `zlib-1.2.13`

Still getting compilation error
![image](https://user-images.githubusercontent.com/2981715/210683368-02ed8730-d118-4cab-aa8f-bdefb9840bd3.png)

**Comment by mksdev** [comment]
You can check the https://github.com/firoorg/firo/pull/1226 if you need to build your own image

**Comment by skironDotNet** [comment]
I just took ready compiled firo and added to base Ubuntu image and it works. It makes no sense to compile in docker container
