### ISSUE TITLE
Typo issue on french QT - Firo Core Wallet (Mainnet)

### ISSUE THREAD

**Issue by Zozo2929** [firoorg/firo#1272]
![20230731_164900](https://github.com/firoorg/firo/assets/141049484/dfa0a153-5088-4230-a70b-064f2b47057d)

### Describe the issue

Typo on the word "Evoyer" on the down-left  corner on the French version of Firo QT Core Wallet on the Mainnet .

The word should be written "Envoyer" as shown on the picture .

### Any extra information that might be useful in the debugging process.

Perdonnal address for eventual reward :)

aCD13qKEo2zQYF6qdZrPPPPx8UTMTHEJQs

**Comment by justanwar** [comment]
Tipped via Tipbot

**Comment by Zozo2929** [comment]
Thx 😉

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by Zozo2929** [comment]
aNUpxeUgLgn67ynRvo1TVrS4LEf6gMYpQj

**Comment by Zozo2929** [comment]
Thx ;)

**Comment by Zozo2929** [comment]
> Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

aNUpxeUgLgn67ynRvo1TVrS4LEf6gMYpQj

**Comment by Zozo2929** [comment]
Thx ;)

**Comment by Zozo2929** [comment]
Received, many thanks 😀

**Comment by justanwar** [comment]
TXID: [70b78ed10b3899e5b0718f34bf7ffcef714d0874581637b2e4996eeb563365e0](https://explorer.firo.org/tx/70b78ed10b3899e5b0718f34bf7ffcef714d0874581637b2e4996eeb563365e0)
