### ISSUE TITLE
Spark to Transparent Address Tx does not show in "Transactions" tab of Firo-QT wallet

### ISSUE THREAD

**Issue by Avalance113** [firoorg/firo#1273]
Spark to Transparent Address Tx does not show in "Transactions" tab of Firo-QT wallet. It only shows up after restarting the wallet.

**Comment by justanwar** [comment]
Unable to reproduce.

Is this a spark to transparent (address in own wallet) or spark to transparent (external address)?

**Comment by levonpetrosyan93** [comment]
Me and @levoncrypto also were not able to reproduce.
