### ISSUE TITLE
at "view at block explorer" option

### ISSUE THREAD

**Issue by 77explode** [firoorg/firo#1275]
I think that option like "view at block explorer" would come in handy...
![2023-07-31 21 35 17](https://github.com/firoorg/firo/assets/141067157/8eaa047e-5cdf-4ad1-ad05-18af90339ffb)

**Comment by justanwar** [comment]
On macOS: `Firo Core -> Preferences -> Display -> Third party transaction URLs` and enter `https://testexplorer.firo.org/tx/%`

On Windows/Linux: `Settings -> Options -> Display -> Third party transaction URLs` and enter `https://testexplorer.firo.org/tx/%`
