### ISSUE TITLE
switcher fix

### ISSUE THREAD

**Issue by 77explode** [firoorg/firo#1276]
Some unsigned switcher that looks strange at macOS
<img width="310" alt="Screenshot at Jul 31 21-36-49" src="https://github.com/firoorg/firo/assets/141067157/26758d58-f43d-4b03-a3cb-5c3de13cf2cb">

**Comment by levonpetrosyan93** [comment]
Fixed with #1305

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by 77explode** [comment]
> Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

a3BV7sBFFpjy9nkFLPhkZ7hA2vKWCsk713

thanks

**Comment by justanwar** [comment]
TXID: [69a2b985b064ad8f47f60575a0c8b5dcb1d20f108d50310d978c883661ffdcb4](https://explorer.firo.org/tx/69a2b985b064ad8f47f60575a0c8b5dcb1d20f108d50310d978c883661ffdcb4)

Bounty paid
Type: UI
Amount: 5 Firo
