### ISSUE TITLE
Sync hangup on 107006

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1277]
### Describe the issue
**.1** firod/firo-cli -> **.4** firo-qt,  sync hang up on block 107006
**.4** firo-qt will post error message
can recreate with **.4** syncing with **.1**, 107006 consistent.
can not recreate with empty ~/.firo
error persists after reindex

### Local setup

Manjaro x86_64 - Linux 6.4
**old**(v0.14.12.1) 
**new**(v0.14.12.4)

### Any extra information that might be useful in the debugging process.
fresh install 14.12.1 - sync firod - stop firod - run 14.12.4 bin/firo-qt -testnet

![new-testnet-qt-getblockcount](https://github.com/firoorg/firo/assets/78511436/ed56c777-dd09-4f25-b3b6-64e042e84d97)

![db-error](https://github.com/firoorg/firo/assets/78511436/4b5c1457-812c-4c70-b93a-64a70f306560)
![getblockcount](https://github.com/firoorg/firo/assets/78511436/b9bf3e69-9db0-4f98-a984-dc19fcccfaba)

**Comment by RESTfulRaccoon** [comment]
Replicated on Kubuntu 23.04

Error persists when using **14.12.1**qt

**Comment by RESTfulRaccoon** [comment]
[main-cut-debug.log](https://github.com/firoorg/firo/files/12243517/main-cut-debug.log)

[spark-cut-debug.log](https://github.com/firoorg/firo/files/12243519/spark-cut-debug.log)

from Kubuntu machine

**Comment by justanwar** [comment]
This is expected as there is a protocol change from .1 to .4. 

Block 107007 `fd697486d017f97de23dd45a19bfaabfe85601013824cd795cc12524f3ec1e30 ` also contains a Spark transaction which v0.14.12.1 could not process, and moving to v0.14.12.4 with this issue will show an 'Error loading block database' message and require you to reindex.

Even after reindexing, it might end up on the wrong chain (107117 `80f2182a24c4d04c910220db9c2b4a91be98936a69a7c6bb44ab2205cc51ea25`) if the peers are outdated. The wallet can jump to the correct chain if these peers are disconnected.
