### ISSUE TITLE
Unable to spend max Firo -fee included

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1279]
### Describe the issue

When trying to send max balance with fee subtracted, error received

### Local setup

Manjaro - Linux 6.4
Firo - v0.14.12.4
### Any extra information that might be useful in the debugging process.

![balance_test_float0](https://github.com/firoorg/firo/assets/78511436/bf52e3d2-1c0d-4684-918c-4b77fdff50e6)

![send_test_float0](https://github.com/firoorg/firo/assets/78511436/d540e5e1-e348-43a9-bd62-0aae7c0b2cfc)

![send_test_float1](https://github.com/firoorg/firo/assets/78511436/15300bde-e923-4b5a-94fe-71191770d968)

**Comment by nrsimha** [comment]
Same issue on MacOS version (Firo Core version v0.14.12.4-g0f292f6f0 (64-bit).

First it shows this error:
<img width="349" alt="image" src="https://github.com/firoorg/firo/assets/2452933/fbcf9c7a-3ad2-4fc6-860e-80a0cbd47d1c">

And after closing that error it shows this:

<img width="345" alt="image" src="https://github.com/firoorg/firo/assets/2452933/ee5973d0-c51a-4356-827a-ea3f9823b37d">

**Comment by justanwar** [comment]
Reproducible.

**Comment by levonpetrosyan93** [comment]
Fixed in [d41e5d0cf34d1729f823d92f99940221a934a647](https://github.com/firoorg/firo/commit/d41e5d0cf34d1729f823d92f99940221a934a647)

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by RESTfulRaccoon** [comment]
a3BacgFxzAgkG1dSBYLyi5r3s5rbU3nXVi

**Comment by justanwar** [comment]
TXID: [63b7af1550526519998c7105b0d76a68bdf571bbd9c97849e946d4408044f123](https://explorer.firo.org/tx/63b7af1550526519998c7105b0d76a68bdf571bbd9c97849e946d4408044f123)
