### ISSUE TITLE
Balance confusion

### ISSUE THREAD

**Issue by 0LukeBr** [firoorg/firo#1280]
I'm confused about the balance because first I received the 102.188888 FIRO from different people.. now because I also tried to send to other people I noticed that the FIRO that should be in the Available balance went back to pending and I can't send to other people again, what if I send money to many people, do I have to wait for the pending balance to be added to the available balance because it will take a long time because if I have to wait? 

![1](https://github.com/firoorg/firo/assets/141116151/4c725327-c8cc-4a3d-b069-ef3d25f98155)
![2](https://github.com/firoorg/firo/assets/141116151/df001777-3256-42e4-b37a-9b0237f7700d)

 Windows 10 , testnet QT version 5.12.11

**Comment by 0LukeBr** [comment]
now after a couple of minutes i notice that pending balance is back again in the available balance.. 
![3](https://github.com/firoorg/firo/assets/141116151/66a8bb38-9287-4fd9-b6f5-2fda0864d612)


so im confuse, Do we have to wait back in available balance before we can send again?

**Comment by justanwar** [comment]
Yes, the resulting output mint from the initial tx must move to the available section before being spendable again.

**Comment by 0LukeBr** [comment]
thanks anwar. now understand :D
