### ISSUE TITLE
Resizing columns on Transactions tab resizes whole app  

### ISSUE THREAD

**Issue by nrsimha** [firoorg/firo#1281]
### Describe the issue

When in Transactions tab if I try to resize any columns (e.g. Amount, Address / Label, Type, Date) it somehow increases width to Address/Label column and app gets wider and wider.

https://github.com/firoorg/firo/assets/2452933/7cb60121-3ce3-42e0-a948-60bc3289cf04

### Local setup

OS: Macos Ventura 13.4.1 (22F82)
Firo QT: Firo Core version v0.14.12.4-g0f292f6f0 (64-bit)

**Comment by RESTfulRaccoon** [comment]
Same on Manjaro - Linux 6.4

**Comment by justanwar** [comment]
Similar to #1099

**Comment by levonpetrosyan93** [comment]
Fixed with #1305

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by nrsimha** [comment]
aHsxp3D17Nud3n3Sc3UnV8Biph5m3CvaRz

**Comment by justanwar** [comment]
TXID: [bff909286fa5c2eab9e200f97fd87a86183afb052277ee3816b7672bbf2c329a](https://explorer.firo.org/tx/bff909286fa5c2eab9e200f97fd87a86183afb052277ee3816b7672bbf2c329a)
