### ISSUE TITLE
Debit showing as 0 for sent tx

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1282]
### Describe the issue
Debit for sent tx shows 0 in transaction details (should be 1), net amount correct
### Local setup

Manjaro - Linux 6.4
Firo - v0.14.12.4

### Any extra information that might be useful in the debugging process.

![incorrect-debit-amount](https://github.com/firoorg/firo/assets/78511436/b305b1ab-3205-4511-afa7-b3da802e78de)

![incorrect-debit-amount_1](https://github.com/firoorg/firo/assets/78511436/2bb49938-1c54-41b5-93fb-03ea2da58308)

**Comment by justanwar** [comment]
Is this a Spark or transparent transaction?

**Comment by RESTfulRaccoon** [comment]
Spark

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by RESTfulRaccoon** [comment]
a3BacgFxzAgkG1dSBYLyi5r3s5rbU3nXVi

**Comment by justanwar** [comment]
TXID: [659a4c3ac3e9d26ea9271e6595abefcffe7f947d40f75604ef67977ffdac229b](https://explorer.firo.org/tx/659a4c3ac3e9d26ea9271e6595abefcffe7f947d40f75604ef67977ffdac229b)

**Comment by justanwar** [comment]
Fixed in https://github.com/TheArcadiaGroup/firo_spark/commit/1f971513be7549fc8b21d9244eeed6b6db8f2ec8
