### ISSUE TITLE
Unable to send batch tx with fee included

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1283]
### Describe the issue

Attempting to send any amount with "subtract fee" enabled, still get quoted for price with fee

### Local setup
Manjaro - Linux 6.4
Firod - 14.12.4

### Any extra information that might be useful in the debugging process.

![subtract-fee-batch_0](https://github.com/firoorg/firo/assets/78511436/ab45c622-396e-47ef-843e-bc9eb4fd548b)

![subtract-fee-batch_1](https://github.com/firoorg/firo/assets/78511436/6c9a215e-73a8-4802-a8ca-2d13e92044e6)

**Comment by RESTfulRaccoon** [comment]
UI error, sends amount with fee taken out.

**Comment by levonpetrosyan93** [comment]
Fixed in [d41e5d0cf34d1729f823d92f99940221a934a647](https://github.com/firoorg/firo/commit/d41e5d0cf34d1729f823d92f99940221a934a647)

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by RESTfulRaccoon** [comment]
a3BacgFxzAgkG1dSBYLyi5r3s5rbU3nXVi

**Comment by justanwar** [comment]
TXID: [33c873439b08a6e0b028379fb4f3bb9682ade1055cf3adcef9cd65d468befbd6](https://explorer.firo.org/tx/33c873439b08a6e0b028379fb4f3bb9682ade1055cf3adcef9cd65d468befbd6)
