### ISSUE TITLE
Firo-cli spendspark gives error (code -4) with "subtractFee: true"

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1284]
### Describe the issue

firo-cli spendspark gives error (code -4) with "subtractFee: true"

### Local setup

Manjaro - Linux 6.4
Firo - 14.12.4

### Any extra information that might be useful in the debugging process.

![spendspark_0](https://github.com/firoorg/firo/assets/78511436/7148c552-049a-40ed-8338-1052a9c582a8)

![spendspark_1](https://github.com/firoorg/firo/assets/78511436/ab78fdfc-cc4e-45ef-bba7-e4c708eea841)

![spendspark_2](https://github.com/firoorg/firo/assets/78511436/3d62d658-8339-4eba-a474-eec6e1d829c6)

**Comment by justanwar** [comment]
Was the second spend attempted after a Spark transaction got mined?

**Comment by RESTfulRaccoon** [comment]
only difference is the true/false flag.
error persists after a new block is mined

![getblockcount_1](https://github.com/firoorg/firo/assets/78511436/62d4a5ca-30fe-420c-a8b2-5cd7b3bd7114)

[cut-debug.txt](https://github.com/firoorg/firo/files/12243515/cut-debug.txt)

**Comment by levonpetrosyan93** [comment]
Fixed in [d41e5d0cf34d1729f823d92f99940221a934a647](https://github.com/firoorg/firo/commit/d41e5d0cf34d1729f823d92f99940221a934a647)

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by RESTfulRaccoon** [comment]
a3BacgFxzAgkG1dSBYLyi5r3s5rbU3nXVi

**Comment by justanwar** [comment]
TXID: [2eabf4d269eaaaedf1083846e671507487a30428323d43bf9bb938dc6676d859](https://explorer.firo.org/tx/2eabf4d269eaaaedf1083846e671507487a30428323d43bf9bb938dc6676d859)
