### ISSUE TITLE
IDE keeps bind and process active

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1285]
### Describe the issue

When opening debug.log through firo-qt debug console -- if text editor left open, will keep listener running causing error if trying to reset firod 

### Local setup

Manjaro - Linux 6.4
Firo - 14.12.4
Kate - 23.04.3

### Any extra information that might be useful in the debugging process.

![text-editor-open_0](https://github.com/firoorg/firo/assets/78511436/f879548c-14d0-44a8-9118-167dfed50066)

![text-editor-open_1](https://github.com/firoorg/firo/assets/78511436/d30b6308-6ada-42a5-9058-58c3d1815590)

**Comment by RESTfulRaccoon** [comment]
Persists on Kubuntu 23 -- any IDE - tested Kate, VS-OSS and Atom

**Comment by levonpetrosyan93** [comment]
Looks platform specific thing, tested on Ubuntu 20.04.3 with system text editor, and Kate, and no issue.

**Comment by RESTfulRaccoon** [comment]
Could be the environment.
