### ISSUE TITLE
Minor - Firo desktop logo in Linux is greenish instead of red 

### ISSUE THREAD

**Issue by Znod** [firoorg/firo#1286]
Installed latest Linux Testnet on ubuntu using firo-0f292f6f0390-x86_64-linux-gnu.tar.gz 
and got a greenish logo to my surprise as per attachment. ;-)
Looking forward to the real testing!

![Firo_logo_green_testnet](https://github.com/firoorg/firo/assets/68607087/ea670832-d279-4ca8-bd3f-13a37a4a2e76)

**Comment by RESTfulRaccoon** [comment]
that signifies you are running testnet

**Comment by justanwar** [comment]
Not a bug unfortunately.

Red for mainnet, yellow-green for testnet, green for regtest.

**Comment by Znod** [comment]
Happy days! Smart move to use different colors for dev, test prod.
