### ISSUE TITLE
New Spark address created via debug console not shown in receiving addresses

### ISSUE THREAD

**Issue by Znod** [firoorg/firo#1288]
### Describe the issue
When creating a new spark address via console the address does not show up in receiving addresses. For transparent addresses it works. (see attached video) 

Also

debug command "getprivatebalance" returns 0.00.... despite a balance as per screenshot
debug command "listaddressbalances 0.01" shows {} despite several (spark) balances exist (maybe we need a "listsparkaddressbalances" command? - while I would prefer to see all (transparent and spark addresses with such a command))

as per screenshot

### Local setup
Ubuntu 22.04 running Testnet v0.14.12.4-g0f292f6f0

![Screenshot from 2023-08-02 13-22-12](https://github.com/firoorg/firo/assets/68607087/07e9ea73-c521-4d28-8ed3-039c0c9c5f1d)

**Comment by Znod** [comment]
[Screencast from 02-08-23 13:13:47.webm](https://github.com/firoorg/firo/assets/68607087/06cce627-4420-420e-aa60-e6d6d81a1c77)

**Comment by justanwar** [comment]
Reproducible.

For balance issues, we have `getsparkbalance` but probably not what you are looking for. Please open a new separate issue.

**Comment by Znod** [comment]
> `getsparkbalance`

Thanks - getsparkbalance does what I need. as per above by RESTfulRacoon getprivatebalance seems redundant with spark?

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by Znod** [comment]
aPY4WVstEVgppZKbgcwP7Xxw2KoNt1sJwg

Thanks! It´s a pleasure testing Firo!

**Comment by justanwar** [comment]
TXID: [323a1f0314c69243d0e90272ebd59bccc6aa96fb7c441c79899ada6cbc01f771](https://explorer.firo.org/tx/323a1f0314c69243d0e90272ebd59bccc6aa96fb7c441c79899ada6cbc01f771)

Bounty paid:
Type: UI
Amount: 5 Firo

**Comment by justanwar** [comment]
Fixed in https://github.com/TheArcadiaGroup/firo_spark/commit/1f971513be7549fc8b21d9244eeed6b6db8f2ec8
