### ISSUE TITLE
Console command "getprivatebalance" redundant?

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1290]
![getprivatebalance](https://github.com/firoorg/firo/assets/78511436/17c033e5-1639-4bb9-930c-4f1bd4e96ec0)

**Comment by RESTfulRaccoon** [comment]
similar to #1288 closing

**Comment by justanwar** [comment]
Reopening, on #1288 that issue is secondary.

Currently `getprivatebalance` returns Sigma and Lelantus balance only when it should have returned all 3 (Sigma, Lelantus, and Spark)

**Comment by levonpetrosyan93** [comment]
In #1296 spark balance alsi included into getprivatebalance result, but for now we decided to keep getsparkbalance rpc to get only spark balance.

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by RESTfulRaccoon** [comment]
a3BacgFxzAgkG1dSBYLyi5r3s5rbU3nXVi
