### ISSUE TITLE
[BUG] When creating a new wallet, if you do a simple mouse click, the seed phrase disappear 

### ISSUE THREAD

**Issue by hakonamatata** [firoorg/firo#1291]
### Describe the issue

When creating a wallet, you do not need to verify the seed phrase. If you click, it disappear. Making it very easy to start using the wallet, never seeing or verifying the seed words. 

You should not be allowed to continue before double checking that the user has indeed the correct seed phrase written down. 

### Local setup
Windows 10, latest version of Firo, testnet

### Any extra information that might be useful in the debugging process.

here you can see: 
![firo-close-bug](https://github.com/firoorg/firo/assets/4003969/149a68a4-1414-459d-80bc-ef656ff32a46)

**Comment by justanwar** [comment]
Could you try minimizing the main wallet window to see if the seed phrase window is hidden behind it? (or Alt+Tab)
