### ISSUE TITLE
Certain transactions not locked by InstantSend on testnet

### ISSUE THREAD

**Issue by justanwar** [firoorg/firo#1298]
![image](https://github.com/firoorg/firo/assets/42809091/06a4c168-33dc-42eb-b206-2c02f8834b7f)

On testnet it appears that some transactions are not InstantSend-locked even after the transaction in question has exited Dandelion.

IS-Locked:

- Transparent to Spark (mint)
- Transparent to Transparent

Not IS-locked:

- Spark to Spark
- Spark to Transparent

**Comment by justanwar** [comment]
Created 10 transparent-to-transparent transactions within a short period of time. All were InstantSend-locked.

**Comment by nrsimha** [comment]
Not sure if this is related to this or if I should create new issue.

I made transactions to Lucas during today event and now after almost 1 hour there are few transactions 0/unconfirmed, in memory pool. It is like every fourth transaction is not finished and pending.

<img width="862" alt="image" src="https://github.com/firoorg/firo/assets/2452933/de652ead-2630-4c39-9a19-c4d1af820593">

And private balance still pending:

<img width="280" alt="image" src="https://github.com/firoorg/firo/assets/2452933/fe4da28c-e3df-4c65-a06a-a332530d07c0">

**Comment by justanwar** [comment]
@nrsimha Your issue is the same as #1297 (which was opened by you). My issue is the lack of IS-lock, which is indicated by the lack of key icon in transaction list. You can try it out by doing a transparent-to-transparent transaction and see if it is locked.

**Comment by levonpetrosyan93** [comment]
Fixed in commit [39510e31b4d45bdb058440ad110b134e197ebb27](https://github.com/firoorg/firo/commit/39510e31b4d45bdb058440ad110b134e197ebb27)
