### ISSUE TITLE
Adress / Label in Transactions view is not showed for Spark transactions

### ISSUE THREAD

**Issue by nrsimha** [firoorg/firo#1299]
### Describe the issue

When sending with Spark there is no address (or label) to which Firo has been sent to. Column for Address / Label shows '(n/a)'.
I would expect there will be either label of address I sent transaction to or address (in case label is not defined).

<img width="143" alt="image" src="https://github.com/firoorg/firo/assets/2452933/c4f78ce9-0cc1-448b-988c-211f43a0a7af">

### Local setup

OS: Macos Ventura 13.4.1 (22F82)
Firo QT: Firo Core version v0.14.12.4-g0f292f6f0 (64-bit)

### Any extra information that might be useful in the debugging process.

Proper label shows only when receiving to transparent address.

To duplicate. Add Spark address with label. Send Firo to that address. Go to Transactions view and there is `(n/a)` as Address/ Label for that transaction.

By showing details of the transaction there is also not listed address to which was it send:

<img width="679" alt="image" src="https://github.com/firoorg/firo/assets/2452933/e97505fb-1e9e-40e0-b0db-455037a7c475">

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by nrsimha** [comment]
aNGP5hUXBNsp1PVNXwNwf4rvAsfiu2KDM6

**Comment by justanwar** [comment]
TXID: [46fdf2303c332963d821c1b200631bc313694d5f7a9542853d7d24384142ff67](https://explorer.firo.org/tx/46fdf2303c332963d821c1b200631bc313694d5f7a9542853d7d24384142ff67)

**Comment by justanwar** [comment]
Fixed in https://github.com/TheArcadiaGroup/firo_spark/commit/c85236da0e08bdeb915b92506773f17ea199559f
