### ISSUE TITLE
GUI - Detail view on receive tab not fully shown - need to manually expand

### ISSUE THREAD

**Issue by Znod** [firoorg/firo#1303]
Using v0.14.12.4-g0f292f6f0 Testnet on ubuntu 22.04.3 / Gnome 42.9

When creating a new receiving address (Transparent or Spark) or opening an existing via "Show button" or doubleclick the detail view does not show all information. You need to resize the window manually to see label and address type. Minor issue (as this info is shown on main screen also) but nice to have seeing all info at once. Video attached.

[Screencast from 09-08-23 14:58:59.webm](https://github.com/firoorg/firo/assets/68607087/7510f787-4fb6-4172-bfa7-f974ed101bc8)

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by Znod** [comment]
a8CbnWqzfLdMSwvMdwaUSwVJw71upTUPxy

Thanks!

**Comment by justanwar** [comment]
TXID: [8b56ea7c595b5c70b64b29b9abd3e02a602484789988835e159e5b16bfe4cd76](https://explorer.firo.org/tx/8b56ea7c595b5c70b64b29b9abd3e02a602484789988835e159e5b16bfe4cd76)

Bounty paid:
Type: UI
Amount: 5 Firo

**Comment by Znod** [comment]
Awesome thanks!

**Comment by justanwar** [comment]
Fixed in #1306
