### ISSUE TITLE
GUI - "Znode" was POSE banned 

### ISSUE THREAD

**Issue by Znod** [firoorg/firo#1304]
Minor:  Might want to consider renaming "Znode" to "Firo Server" ... ;-) while this name was inspiration for my github profile ... tempus fugit.
![Screenshot from 2023-08-09 14-42-51](https://github.com/firoorg/firo/assets/68607087/24239cbb-43d2-4aba-b380-10ff6fa99baa)

**Comment by justanwar** [comment]
Similar to #959
