### ISSUE TITLE
curl method "spendspark" returns server error 500 

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1308]
### Describe the issue
```
curl -v --user $USER:$PASS --data-binary '{"jsonrpc":"1.0", "id":"something", "method": "spendspark", "params": ["{\"$ADDR\":{\"amount\":1, \"memo\":\"\", \"subtractFee\": false}}"] }' -H 'content-type: text/plain;' http://127.0.0.1:8382/
```

Returns:
>HTTP/1.1 500 Internal Server Error
>Content-Type: application/json
>Date: Mon, 14 Aug 2023 20:33:19 GMT
>Content-Length: 105

`./firo-cli "{\"$ADDR\":{\"amount\":1, \"memo\":\"\", \"subtractFee\": false}}"` 

work as expected, no wallet encryption 

Other curl methods such as:
"getnewsparkaddress" and "getinfo" and "getsparkbalance" work as expected
### Local setup

Manjaro - Linux 6.4
Firo 14.12.04
### Any extra information that might be useful in the debugging process.
Using an invalid address causes the same error
No relevant logs available

**Comment by RESTfulRaccoon** [comment]
Error acts as if perams is empty `"perams": [""]` returns same error

**Comment by RESTfulRaccoon** [comment]
method `mintspark` returns same error
seems anything requiring parameters returns the error

`{"result":null,"error":{"code":-1,"message":"JSON value is not an object as expected"},"id":"something"}`

**Comment by justanwar** [comment]
Please try with latest commit from [spark branch](https://github.com/firoorg/firo/tree/spark) (daemon only, Qt does not have Spark UI.) Let me know if you need the binaries.

**Comment by RESTfulRaccoon** [comment]
![spendspark_test](https://github.com/firoorg/firo/assets/78511436/7fadecb9-ec47-4075-a7a1-404377be33b2)

working

**Comment by RESTfulRaccoon** [comment]
![spendspark_3](https://github.com/firoorg/firo/assets/78511436/796fd32c-0dfb-4a73-8834-53c53808b1fd)

same error, but to be honest I'm not the best with git so could be on my end.

**Comment by mobias17** [comment]
It seems to be the parser and not an server issue.

![image](https://github.com/firoorg/firo/assets/48771525/8445e3bb-68e1-4091-9818-ce180a24ef4c)

Three examples:
`spendspark` to a single address - success
`spendspark` to signle address - fail. Note the `[` and `]` as only difference to before.
`spendspark` to multiple address - success | lining up the params without squared brackets

I agree that one example in the help is with square brackets. So question to Project is whether it is a documentation issue or parser issue. 

@RESTfulRaccoon  would you mind to run a retest without square brackets and confirm observation?

here the param templates :

spendspark "{\"ADDRESS1\":{\"amount\":1,\"memo\":\"\", \"subtractFee\": false}}"
spendspark ["{\"ADDRESS1\":{\"amount\":1,\"memo\":\"\", \"subtractFee\": false}}"]
spendspark "{\"ADDRESS1\":{\"amount\":1, \"memo\":\"test_memo\", \"subtractFee\": false},\"ADDRESS2\":{\"amount\":1, \"subtractFee\": false}}"

**Comment by RESTfulRaccoon** [comment]
![brackets.png](https://github.com/firoorg/firo/assets/78511436/2ecb6c6a-75ca-4cd8-b7d9-6ac6a8bc92ac)

![brackets_2.png](https://github.com/firoorg/firo/assets/78511436/085b7054-2535-4ed9-9955-1c88071d921d)

![backslash.png](https://github.com/firoorg/firo/assets/78511436/75462bfe-f9e0-458a-bd5b-c13d9e019cef)

![backslash_2.png](https://github.com/firoorg/firo/assets/78511436/0de3c9b4-30f3-4cb0-a8bc-c6f0940e198f)

**Comment by mobias17** [comment]
apologies. I checked the code and now below the `curl ` commands:

amend username, address and port accordingly.
single:
`curl -v --user MYUSERNAME --data-binary '{"jsonrpc": "1.0", "id":"something", "method": "spendspark", "params": [{"ADDRESS1":{"amount":0.01, "subtractFee": false}}] }' -H 'content-type: text/plain;' http://127.0.0.1:PORT/`

multiple:
`curl -v --user MYUSERNAME --data-binary '{"jsonrpc": "1.0", "id":"something", "method": "spendspark", "params": [{"ADDRESS1":{"amount":0.01, "subtractFee": false},"ADDRESS2":{"amount":0.01, "subtractFee": false}}] }' -H 'content-type: text/plain;' http://127.0.0.1:PORT/`

proof:

![image](https://github.com/firoorg/firo/assets/48771525/44deeffb-d6be-43c6-92af-056d1169d5f1)

single - returns 200
![image](https://github.com/firoorg/firo/assets/48771525/b567db6e-e732-44c9-b3f4-49fbc4f56272)

multiple - return 200
![image](https://github.com/firoorg/firo/assets/48771525/e8f811cc-c62d-468f-a108-afa0f04dc0ef)

**Comment by levonpetrosyan93** [comment]
Fixed with [881ff260d3b459d8b2e6eaa5c089eec35c385d47](https://github.com/firoorg/firo/commit/881ff260d3b459d8b2e6eaa5c089eec35c385d47) , Feel free to reopen, in case issue again happens.

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by RESTfulRaccoon** [comment]
a3BacgFxzAgkG1dSBYLyi5r3s5rbU3nXVi

**Comment by justanwar** [comment]
TXID: [0c73d47b082b69d584c2719951eea64b859f432ac92a35d711bb96503afc64e2](https://explorer.firo.org/tx/0c73d47b082b69d584c2719951eea64b859f432ac92a35d711bb96503afc64e2)

Bounty paid:
Type: UI
Amount: 5 Firo
