### ISSUE TITLE
Update python

### ISSUE THREAD

**Issue by Kiirocoin** [firoorg/firo#1309]
Hello
will be good to avoid errors, update python  command for apt install to python3, if u have ubuntu22, change doc/build-unix.md and readme.md

`sudo apt-get install git curl python build-essential libtool automake pkg-config cmake`

replace with

`sudo apt-get install git curl python3 build-essential libtool automake pkg-config cmake`

**Comment by justanwar** [comment]
We kept it at `python` because the minimum version required to build is Ubuntu 18.04
