### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by basirairdrop** [firoorg/firo#1313]
masternode not showed as mine in firo client

Spark : st1n8nadzntjygm0et0nl3znsrt6kxfrmgrcfpukvn93zh25dvzw5w62ddznh5fr0pukv47rws0pyt99uqv0ss7zz8x8jsfvyr0xxmx4r8r34k0fmj2jhemn9v2pdht7c5mmeuuvjs53qnwk

Transperent : TY2bbCfpXmahMYb2G58RpRNNRoaFtNqDej

**Comment by justanwar** [comment]
Duplicate of #1222
