### ISSUE TITLE
synchronization at the beginning was a little too long

### ISSUE THREAD

**Issue by Danblue08** [firoorg/firo#1316]
great project, I hope this project can be even better when mainnet arrives. need to improve like UI/UX or other menus. I believe in the developers and the team behind all this, synchronization at the beginning was a little too long maybe it can be accelerated again, maybe that's all I need to say, warm greetings from me.

![Screenshot 2023-08-28 014700](https://github.com/firoorg/firo/assets/101073001/82db3c1f-e7e4-4657-a66c-24ec6baa4dd8)

**Comment by justanwar** [comment]
The time shown is the blockchain time, not how long it takes to sync.
