### ISSUE TITLE
facets not working

### ISSUE THREAD

**Issue by OneNov0209** [firoorg/firo#1320]
hello team,, I have successfully operated the wallet testnt.  after I took the faucet, but until now the balance is still empty, I have refreshed my wallet several times, but it is still empty.  any solution for this?  Next, I will send a photo of the proof of the wallet, and the hash of the transaction. Thanks
https://testexplorer.firo.org/tx/ce80a3224e823df0a0cea7bba883fa6652623efd64ce11e462b8dec5ba48f90b
![IMG_20230828_122224_424](https://github.com/firoorg/firo/assets/95606017/f5497719-5fac-4bc4-8fe5-cb7c93d4742e)
![IMG_20230828_122222_325](https://github.com/firoorg/firo/assets/95606017/7d630d7e-33cf-49e4-859f-44f5097c9075)

**Comment by justanwar** [comment]
You need to be fully synced to see recent transactions.

**Comment by OneNov0209** [comment]
Ok mate,, tahnks
