### ISSUE TITLE
The wallet starts immediately without re-entering keywords to confirm

### ISSUE THREAD

**Issue by Salams3hat** [firoorg/firo#1324]
12 wallet recovery keywords do not appear, immediately activate without reconfirming 12 or 24 keywords,network synchronization eats up high cpu usage 100% takes long term sustainability procescor usage may not be friendly for 4 gb ram which only has 2 processors.
my tranparnt test addres:
TRYWqvDuuBjk38eedn4ENg1nhUz7L9q8uu

**Comment by justanwar** [comment]
Have you checked if the window is hidden, like https://github.com/firoorg/firo/issues/1291 ?
