### ISSUE TITLE
UI :: QR Code --> address underneath

### ISSUE THREAD

**Issue by mobias17** [firoorg/firo#1327]
In the Receive section a QR code is generate with the Information. Underneath the 144 Char long address is printed, however it can be displayed only 42.  Further the displayed chars are from the middle and not e.g. first or last 42 characters.

Would be handy to have the first `n` and last `n` characters underneath, so if ever you want to compare a saved QR code to the address it is simpler. Further, if I am nit mistaken with the first char you can see whether it is mainnet or testnet address

![image](https://github.com/firoorg/firo/assets/48771525/588a18c6-5a36-4446-9380-dae0a66911b5)

#### simplified code before passing to QR-generator

```
#include <iostream>
#include <string>

using namespace std;

int main()
{
    std::string Address="st1sve9neksxw2y4renktwx8xfkhx6vpp8q8u9pfduys2nz0exj62xd7sv0khyz0j98s4hs7qeegu5yvtzcgluf6yc8sghl8d7e68ep9c8vgyaz5wv8keqyxjkngxnfyxuk38rg8csf8pssp";
    
    std::string AddressUnderQrCode = Address.substr(0,16) + " . . . " + Address.substr(Address.size() - 16);
    cout<< AddressUnderQrCode ;
    

    return 0;
}
// st1sve9neksxw2y4 . . . xuk38rg8csf8pssp
```

**Comment by levonpetrosyan93** [comment]
Fix in commit [cb88319262ae1b1baa0572a9becf11b7c84c1e4f](https://github.com/TheArcadiaGroup/firo_spark/commit/cb88319262ae1b1baa0572a9becf11b7c84c1e4f)

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by mobias17** [comment]
aHQSNkHY2Q7LMdgABd8zWEssWyDVAHUBYW

**Comment by justanwar** [comment]
TXID: [5a4c979cd2eeafe67932e34c55a5a76cfa0e2d1f19332939222a87b41bf097f3](https://explorer.firo.org/tx/5a4c979cd2eeafe67932e34c55a5a76cfa0e2d1f19332939222a87b41bf097f3)

Bounty paid:
Type: UI
Amount: 5
