### ISSUE TITLE
Getwalletinfo returns zero as balance.

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1329]
### Local setup

Manjaro 6.4

### Any extra information that might be useful in the debugging process.
![getwalletinfo.png](https://github.com/firoorg/firo/assets/78511436/e5de4873-bfc6-4154-8641-ddb3aa0d9d2f)

**Comment by justanwar** [comment]
`getinfo` and `getwalletinfo` only shows transparent balances.
