### ISSUE TITLE
removetxmempool uncomplete

### ISSUE THREAD

**Issue by mobias17** [firoorg/firo#1333]
### Describe the issue

![image](https://github.com/firoorg/firo/assets/48771525/64814456-1ccb-41fb-ba23-401330cdb822)
![image](https://github.com/firoorg/firo/assets/48771525/bf3dcdc2-37ab-4341-a22e-3371c9eb13ae)

the function `removetxmempool `  is uncomplete. Forgotten, depreciated, defered to later

### Local setup
![image](https://github.com/firoorg/firo/assets/48771525/81010d81-0624-46a1-bcd1-663eb87a28ea)

**Comment by levonpetrosyan93** [comment]
Fixed ad [21586cb42186d4b1ce0ba75c2b9d0467693855f4](https://github.com/firoorg/firo/commit/21586cb42186d4b1ce0ba75c2b9d0467693855f4)

**Comment by justanwar** [comment]
Please reply to this post with a mainnet Firo address for the bug bounty payout. Use a new address that has never been used before. Make sure to anonymize after receiving!

**Comment by mobias17** [comment]
@justanwar sorry for the delay in responding and thank you! a6Y6jAVER23qe9K9uUaRW6kQMK7bKEQNNr

**Comment by justanwar** [comment]
TXID: [ba34c1b2b81957cf030de95efbc9bba8f84449961ca4d8b5c77549f85730132c](https://explorer.firo.org/tx/ba34c1b2b81957cf030de95efbc9bba8f84449961ca4d8b5c77549f85730132c)

Bounty paid:
Type: UI
Amount: 20
