### ISSUE TITLE
Referenco to Znode in warning on dumpprivkey command

### ISSUE THREAD

**Issue by nrsimha** [firoorg/firo#1350]
### Describe the issue

When running `dumpprivkey ADDRESS` in Firo QT console warning text includes: "...it is not needed for Znode setup or diagnosis"

As Znodes are called just Masternodes, it should be instead:
"...it is not needed for Masternode setup or diagnosis" or "...it is not needed for Firo Masternode setup or diagnosis"

### Local setup
MacOS, Firo Core version v0.14.12.1-gc7e3ef0e6 (64-bit)

**Comment by justanwar** [comment]
We wanted to do it fully which includes both cosmetic (such as this) and the underlying parts such as `znodeblsprivkey` in `firo.conf` and the `evoznode` commands, but would have meant slowing down other major features such as Spark.

Re: #959
