### ISSUE TITLE
Top bar not visibile in firo-qt on Fedora

### ISSUE THREAD

**Issue by erciccione** [firoorg/firo#1354]
### Describe the issue

The top menu has white text on whitish background, making it very hard to read.

### Local setup

OS: Fedora 38
Qt version: 5.15.10
Firo v0.14.12.1

![Screenshot_20231114_082534](https://github.com/firoorg/firo/assets/28106476/0159cba2-ecb5-4563-9ba1-dbb0ca5bd85e)

**Comment by levonpetrosyan93** [comment]
@erciccione What type of appearance  are you using on  your Fedora machine? looks this issue is happening on specific appearance

**Comment by erciccione** [comment]
I'm using KDE Plasma 5.27.9, "Breeze Dark" theme.

**Comment by erciccione** [comment]
#1425

**Comment by erciccione** [comment]
@levonpetrosyan93 could we reopen this until #1425 is merged and confirmed resolved in a release? More duplicated of this issue could be opened if others come to signal the bug. Same for #1416.
