### ISSUE TITLE
"Click here" in migration banner unclickable

### ISSUE THREAD

**Issue by justanwar** [firoorg/firo#1391]
In some circumstances the "Click here" in migration banner is unclickable. The RPC call still works.

![image](https://github.com/firoorg/firo/assets/42809091/5de12b65-3ffc-4985-ac5f-a60597a6252b)

**Comment by nrsimha** [comment]
I have same issue on MacOS. 
Firo Core version v0.14.13.0-g39c41e5e7 (64-bit)

**Comment by Dubaiali** [comment]
@justanwar Got the same issue. Can someone explain RCP Call and where to do that?

**Comment by justanwar** [comment]
Known workarounds (independent of each other):
1. Unlock wallet with `walletpassphrase "YOURPASSWORD" 30` in the Debug Console. The migrate banner should be clickable now.
2. Go to Send tab and attempt a transparent Send. A window should pop up asking you to go private. Proceed to private, then another window should pop up asking you to migrate from Lelantus to Spark.
3. Use the `lelantustospark` RPC in the Debug Console.
4. Use the `joinsplit` RPC in the Debug Console to spend Lelantus to a transparent address, then send those to Spark.

Attempting to use the Send -> Private Balance to send Lelantus to Spark will not work.

**Comment by goodc0re** [comment]
@justanwar, the workaround options cause Firo Core on macOS Sonoma 14.2.1 to become unresponsive and it needs to be force quit. After each force quit it needs to sync that last 36 hours again. This is on a 32 GB Ram 2,4 GHz 8-Core Intel Core i9 machine. 
The wallet contains only Lelantus outputs. The balance is shown as 0 and the "Click here" in the migration banner is unclickable. 
I tried all the options and so far could not migrate any funds.

**Comment by justanwar** [comment]
@goodc0re Could you try the `joinsplit` RPC method? Create a transparent address and use it as the argument. It is recommended to also open private balance coin control to see how many Lelantus inputs/amount you have and spread it over several joinsplit (Lelantus spend) transactions.

**Comment by goodc0re** [comment]
@justanwar The joinsplit RPC method also results in Firo Core to become unresponsive and needing to be force closed after issuing the command. The wallet had been unlocked prior to issuing the joinsplit command.

**Comment by goodc0re** [comment]
@nrsimha Thanks, it needed a couple of minutes of unresponsiveness and indeed migration worked in the end. A note along the lines of "may take a while" might be useful somewhere in the gui.

**Comment by JCThePants** [comment]
I've been trying to migrate and tried the RPC calls (joinsplit and lelantustospark). They appear successful but when I check the transaction, it says "0/offline, has not been successfully broadcast yet". If I try to rebroadcast, I get a dialog window that says "There was an error trying to broadcast the message:".

**Comment by justanwar** [comment]
@JCThePants Which transactions failed to rebroadcast? (Lelantus to transparent/transparent to Spark?) Are those transactions by any chance exceeding 140kB? We have a fix for this already but it is not released yet. In the meantime, try using smaller amounts to get it below this size.

For reference: https://forum.firo.org/t/lelantus-to-spark-migration-workarounds/3112

**Comment by JCThePants** [comment]
@justanwar I'm attempting to migrate my Lelantus balance and encountered the issue of not being able to use "Click here". I used the workarounds you mentioned here: https://forum.firo.org/t/lelantus-to-spark-migration-workarounds/3112

In all cases, my transactions would not broadcast or re-broadcast. 

The transaction size was 65270 bytes.

I've abandoned the transaction and attempted joinsplit to a transparent address again but using less than the full amount this time and it successfully broadcast.

**Comment by skironDotNet** [comment]
Unlock wallet with walletpassphrase "YOURPASSWORD" 30 in the Debug Console. You should be able to “Click here” in the migration banner.

https://forum.firo.org/t/lelantus-to-spark-migration-workarounds/3112

The only "bug" about is the fact it's not explicitly mentioned on the banner that the wallet needs to be unlocked first

**Comment by levonpetrosyan93** [comment]
Fixed in #1456 ,
