### ISSUE TITLE
Make this a private transaction warning

### ISSUE THREAD

**Issue by nrsimha** [firoorg/firo#1403]
Currently when sending to transparent address it shows this warning:

<img width="511" alt="image" src="https://github.com/firoorg/firo/assets/2452933/ed162252-cc52-43ba-9567-2b73191e1339">

"... If it is masternode transaction, you do not have to go private."

It may be good to include also info about exchanges as at least Binance requires to send from transparent address. And once exchanges will use exchange addresses it will have to be send from transparent for sure.

**Comment by erciccione** [comment]
I suggested an edit to that warning, keeping in consideration your concern: #1436. Feedbacks appreciated :)

**Comment by justanwar** [comment]
Warning reworked in #1434, sending to EX-address reworked in #1448
