### ISSUE TITLE
Cosmetic Error with Firo-QT qcomboboxs

### ISSUE THREAD

**Issue by RESTfulRaccoon** [firoorg/firo#1416]
When selecting from drop down the boxes are over sized, the bottom box also slightly covers the top.
### Local setup

Debian 12, xfce
### Any extra information that might be useful in the debugging process.
![combobox_0](https://github.com/firoorg/firo/assets/78511436/b50821cb-a607-489b-99da-89a8ad61f315)
![combobox_2](https://github.com/firoorg/firo/assets/78511436/bb9606c9-12ee-428b-9a83-dfef599fe6f1)

![combobox_1](https://github.com/firoorg/firo/assets/78511436/36ba9ff9-3d40-4ad1-807e-066044a8987e)

**Comment by skironDotNet** [comment]
Same on Linux Mint

**Comment by brainserenity** [comment]
Same on Ubuntu (22.04 LTS) with KDE desktop environment.

**Comment by skironDotNet** [comment]
```
2024-04-01 14:09:26 GUI: QPushButton(0x558f01c6dad0, name="labelWalletStatus")  does not have a property named  "alignment"
2024-04-01 14:09:26 GUI: QPushButton(0x558f01cc27f0, name="labelTransactionsStatus")  does not have a property named  "alignment"
```

May be related
