### ISSUE TITLE
When exactly will the documentation on the use of the Elysium layer be available?

### ISSUE THREAD

**Issue by unicornlox** [firoorg/firo#1419]
I asked my question on social platforms but there was no one who could answer. so I thought I could get support if I asked here. how can I create my own crypto money with firo? does firo have an api? Should the Elysium layer be used? Is this layer free and if it is free, will it always remain free? Is the Elysium layer paid, that is, will token creation be paid? Can the Elysium layer be used actively and securely at the moment? Is the information about the Elysium layer up to date, or can the information in this information not be used for the time being? When exactly will the Elysium layer become available?

**Comment by justanwar** [comment]
The old Elysium was scrapped since it used the older Lelantus technology. Makes more sense to build a new one based of Lelantus Spark (Spark Assets).

**Comment by unicornlox** [comment]
@justanwar  Is there a roadmap and example of how I can do this with Lelantus Spark (Spark Assets)? where should I start? there is something called spats, how do I use it?  thank you for the information.

**Comment by justanwar** [comment]
@unicornlox Spats/Spark Assets is a WIP and currently not live.
