### ISSUE TITLE
[firo-qt] Top menu isn't readable with a dark UI theme

### ISSUE THREAD

**Issue by brainserenity** [firoorg/firo#1422]
**Top menu isn't readable with a dark UI theme**

**Environment:** Firo Core v0.14.13.2-g0f9d27dfe (64-bit), OS Ubuntu 22.04 LTS, Linux kernel 6.5.0-26-generic (64-bit), KDE Plasma 5.24.7, KDE Frameworks 5.92.0, Qt 5.15.3

**Details:** Bug presents only with a dark theme (i.e. "Dark breeze" default KDE theme). With a light theme everything is OK.
Screenshots added.
![bug1](https://github.com/firoorg/firo/assets/67551367/cc65df15-6c84-4d35-9436-51bc50d0c89f)
![bug2](https://github.com/firoorg/firo/assets/67551367/4cc6262a-9f0b-42d5-a04b-3ec327b6de62)

**Comment by brainserenity** [comment]
Also, in "backup wallet" menu, folder's fonts took same color issue as described in a bug above
![bug](https://github.com/firoorg/firo/assets/67551367/3738c992-b718-43c1-8436-58041379520d)

**Comment by aleflm** [comment]
Can you try running it with the `--style=Oxygen` flag? 

The colour theme problem between KDE / Qt always is present in some way or form in *nix.
