### ISSUE TITLE
Linux build instructions are out of date

### ISSUE THREAD

**Issue by AaronFeickert** [firoorg/firo#1452]
The Linux build instructions indicate that the `python` package is required. However (at least on Ubuntu 24.04 LTS), this is not a valid package. It should be updated to refer to `python3` instead.

**Comment by justanwar** [comment]
The mentioned minimum Ubuntu version is 18.04. If we change it to `python3` anyone on this version will be unable to install it. 

Should we change it to `python3` and add a note for Ubuntu 18.04 to use just `python`?
