### ISSUE TITLE
Cannot start Firo-Qt on a clean install of Ubuntu 24.04 LTS

### ISSUE THREAD

**Issue by dev-warrior777** [firoorg/firo#1479]
### Describe the issue
Cannot start Firo-Qt on a clean install of Ubuntu 24.04 LTS
 
### Local setup

 - Ubuntu 24.04 LTS - Clean install
 - firo-0.14.13.02

### Any extra information that might be useful in the debugging process.
`./firo-qt: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory`

**Comment by dev-warrior777** [comment]
This is a clean install of a new Ubuntu 24.04 system with not much on it but Decred works out of the box, as does Monero so just looks like something that would/should work on a dev box.
Anyway many thanks for looking at this.

**Comment by justanwar** [comment]
Have you tried v0.14.13.3? Does it has the same issue?

**Comment by dev-warrior777** [comment]
> Have you tried v0.14.13.3? Does it has the same issue? Is this release version or self-compiled?

0.14.14.0 release

Just tried on Ubuntu fresh install of Ubuntu 22.04 also. 

`/home/dev/firo/firo-v0.14.14.0/bin/firo-qt: error while loading shared libraries: libxcb-xinerama.so.0: cannot open shared object file: No such file or directory`

As for firo v0.14.13.x .. unknown as I did not check the libraries already installed before starting that version of firo successfully

**Comment by dev-warrior777** [comment]
So on a fresh install this lib seems required

**Comment by dev-warrior777** [comment]
```$ sudo apt search libxcb-xinerama0
Sorting... Done
Full Text Search... Done
libxcb-xinerama0/jammy 1.14-3ubuntu3 amd64
  X C Binding, xinerama extension

libxcb-xinerama0-dev/jammy 1.14-3ubuntu3 amd64
  X C Binding, xinerama extension, development files

**Comment by dev-warrior777** [comment]
I will close this issue as I understand it now & is documented for others

**Comment by dev-warrior777** [comment]
closed with thanks
