### ISSUE TITLE
Sorting of PoSe score on masternode list is alphabetically, should by number

### ISSUE THREAD

**Issue by nrsimha** [firoorg/firo#1482]
### Describe the issue

When on masternode list view and set ordering by PoSe score it sorts score alphabetically (as string), not as number.
If there are nodes with some PoSe score it should sort them as 2576, 2504, 2479, 2479, 25 not as 2576, 2504, 25, 2479, 2479

### Local setup
Firo Core version v0.14.14.0-ge0c423805 (64-bit)
Macos Ventura

### Any extra information that might be useful in the debugging process.

<img width="162" alt="image" src="https://github.com/user-attachments/assets/56a97de9-ec59-4781-a49c-ae9091ef44ac">

**Comment by reubenyap** [comment]
#1483 PR opened to resolve this.

**Comment by justanwar** [comment]
Fixed in #1483
