### ISSUE TITLE
--disable-wallet flag not building due to Znode additions

### ISSUE THREAD

**Issue by stephendliang** [firoorg/firo#204]
I used the instructions to build on https://github.com/zcoinofficial/zcoin/blob/master/doc/build-unix.md and it does not work. I have already successfully built litecoind and bitcoind with their respective instructions, but have stalled on both vertcoind and zcoind on the same machine. 

I did:

```
./autogen.sh
./configure --disable-wallet --disable-miner --enable-zmq
make
```

It was at the make function that things went wrong...

I got this line from the compiler and don't know what happened:

```
CXX      rpc/libbitcoin_server_a-mining.o
rpc/mining.cpp: In function ‘UniValue getblocktemplate(const UniValue&, bool)’:
rpc/mining.cpp:550:10: error: ‘znodeSync’ was not declared in this scope
     if (!znodeSync.IsSynced())
          ^~~~~~~~~
rpc/mining.cpp:550:10: note: suggested alternative: ‘znsync’
     if (!znodeSync.IsSynced())
          ^~~~~~~~~
          znsync
```

I tried replacing the znodeSync with znsync and recompiling but it doesn't work, either...

**Comment by devwarrior777** [comment]
Just had a look at Zcoin - config.ac .. there is no  --disable-miner  so configure will ignore this(edited)
there is also no  --enable-zmq
there is --disable-zmq(edited)
so maybe you change to:
./configure --disable-wallet
and see how it goes

**Comment by devwarrior777** [comment]
just build with vanilla config for now .. if you are space constrained maybe just(edited)
cd src/qt/
rm *.o
rm zcoin-qt

**Comment by riordant** [comment]
https://github.com/zcoinofficial/zcoin/pull/205

**Comment by riordant** [comment]
https://github.com/zcoinofficial/zcoin/issues/235

**Comment by FreakyMaryk** [comment]
the `disable-wallet` flag doesn’t work as Znode code depends on the wallet. After core upgrade this will be fixed.

**Comment by FreakyMaryk** [comment]
Waiting new bitcoin core. We would not plan to fix it right now.

**Comment by riordant** [comment]
IMO, we should close when fix has been implemented. This is a useful reference for people who try to use this flag.

**Comment by qashban4** [comment]
Should be solved when Dash core is updated @psolstice  please add your input on this.
