### ISSUE TITLE
Port of BTCPay server

### ISSUE THREAD

**Issue by reubenyap** [firoorg/firo#241]
BTCPay server allows merchants to accept cryptocurrencies without any intermediaries and is self hosted with plugins for popular CMS.
This should be ported for Zcoin as well for easier integration and less reliance on 3rd party services.
https://github.com/btcpayserver/btcpayserver

Looking for devs who are interested in assisting with this. Bounty available.

**Comment by reubenyap** [comment]
This is in progress now with @sproxet working on it.

**Comment by akshaynexus** [comment]
Is this still available to work on?i dont see zcoin on btcpayserver when i checked on prs recently

**Comment by reubenyap** [comment]
Hi @akshaynexus I'll check with @sproxet!

**Comment by akshaynexus** [comment]
any update?

**Comment by reubenyap** [comment]
Hi @akshaynexus We'll be happy to have you work on it. Contact me at my e-mail reuben@zcoin.io and we can discuss! Thank you!

**Comment by TomaszWaszczyk** [comment]
Any update? There is any spec on that?

**Comment by Onixsr** [comment]
https://twitter.com/BtcpayServer/status/1160216400046297088?s=19

**Comment by ultimaweapon** [comment]
@thebevrishot is currently take a look to see how much works need to be done.

**Comment by qashban4** [comment]
@thebevrishot to complete initial analysis during W42. So we can plan accordingly.

**Comment by thebevrishot** [comment]
After take a look we can follow the document (https://github.com/btcpayserver/btcpayserver-doc/blob/master/Altcoins.md#how-can-i-add-an-altcoin-to-btcpayserver) all task we need to do can  be splited to.

1. Add Zcoin to NBitcoin lib. The document quite not clear much but from example we can take 1 - 2 weeks to implement and create a PR without support mint/spend functionality support.

https://github.com/dgarage/NBXplorer#how-to-add-support-to-my-altcoin
2. Add Zcoin to NBXplorer, this one is tool for track UTXOs. from the example this one is quite simple. but this one require NBitcoin to update version first. Following this https://www.nuget.org/packages/NBitcoin.Altcoins/1.0.5 the maintainer will release ever month. I think we can finish the implementable in a week then at the worst case we need 5 weeks for this.

3. Add Zcoin to btcpayserve I can't find a clear document for this but from example all we need to do is just add some configuration file. This should not take no more than one week to finish it. But we also need to wait NBXplorer too then we need at most 5 weeks for this too.

4. other tasks following docker image, docker compose and cryto definition. This step should be simple and can finish within a week.

The implement is quite simple if we don't need to support mint/spend functionality.  But we need to wait the dependency update, then I think we need at most 3 months to finish it.

**Comment by qashban4** [comment]
This will probably has to wait until ZTM is complete or a new resource is available.

**Comment by akshaynexus** [comment]
Opened a pr to add zcoin to nbitcoin.altcoins.

https://github.com/MetacoSA/NBitcoin/pull/754

**Comment by reubenyap** [comment]
There's an open proposal for this here: https://github.com/zcoinofficial/ccs-proposals/pull/2

**Comment by ultimaweapon** [comment]
@reubenyap do we still need to work on this?

**Comment by reubenyap** [comment]
@ultimaweapon Nope it's low priority there's a current ZCS item on this that is awaiting feedback.
