### ISSUE TITLE
Investigate why built-in miner produced a vout to reward themself with pubkey type instead of pubkeyhash

### ISSUE THREAD

**Issue by ultimaweapon** [firoorg/firo#256]
After talking with Poramin, he concerned about regression. So we need  to careful on this.

**Comment by riordant** [comment]
Is this still an issue following Sigma?

**Comment by ultimaweapon** [comment]
Yes.

**Comment by qashban4** [comment]
Work on this when we have bandwidth.

**Comment by thebevrishot** [comment]
Bitcoin have already removed internal miner since version 0.13

**Comment by ultimaweapon** [comment]
Let's re-check on this once core upgrade is done.
