### ISSUE TITLE
Add option to specify port number to broadcast

### ISSUE THREAD

**Issue by ultimaweapon** [firoorg/firo#259]
This allow Zcoin to run behind port redirection (both by router or Docker).

Related PR: https://github.com/zcoinofficial/zcoin/pull/251

**Comment by FreakyMaryk** [comment]
@ultimaweapon pls update the state of issue.

**Comment by ultimaweapon** [comment]
It is still the issues.

**Comment by thebevrishot** [comment]
Zcoin node will add peers list from message `addr` and sender will add itself to payload then we need to replace sender address and port in payload.

**Comment by ultimaweapon** [comment]
@thebevrishot is Bitcoin already have this feature?
