### ISSUE TITLE
Update instructions how to build Zcoin Fedora23 on Qubes OS

### ISSUE THREAD

**Issue by FreakyMaryk** [firoorg/firo#326]
Devwarrior proposal to test all changes on Fedora23/Qubes OS.
Need to update instruction how to build there and check it before release.

**Comment by devwarrior777** [comment]
What do you need to know .. have you set up Qubes 3.x yet? Did you check PGP that you do not have hacker copy? Have you updated to latest code? Have you created new VM for zcoin yet? Default OS for the VM is Fedora. You will have to increase VM disk size from the default and also increase the RAM size for the VM to enough to run zcoin

**Comment by riordant** [comment]
@FreakyMaryk please follow up

**Comment by qashban4** [comment]
Mariia Kren 11:43 AM
Okay, I would add comment. You can move it to backlog

**Comment by qashban4** [comment]
Moving back to Backlog as its not complete.

**Comment by qashban4** [comment]
@reubenyap Do we still need to support on Fedora23 on Qubes OS or can we close this?

**Comment by devwarrior777** [comment]
Qubes is now at v4.1 and the supported Linux OS versions are:

https://www.qubes-os.org/doc/supported-versions/

So fedora 26, 27, 28, 29, 30 and the debian releases indicated.

Qubes is a secure OS used by many for crypto currency. As the issue initiator I will be upgrading to the (supported) Qubes version 4.1 and will be using one if the supported Fedora versions above to run one crypto per VM. So I think you have to support this subset.

**Comment by ultimaweapon** [comment]
@devwarrior777 I don't quite understand the problem due to the release binary should be able to run on any Linux box. Could you clarify the issue?
