### ISSUE TITLE
Test suite does not function on OSX Mojave

### ISSUE THREAD

**Issue by azilber** [firoorg/firo#517]
```
$ ./src/test/test_bitcoin --log_level=all --run_test=crypto_tests --color_output=0
unknown location:0: fatal error: in "Test setup": boost::runtime::access_to_missing_argument: There is no argument provided for parameter color_output

*** No errors detected
Test setup error: 

```

Attempted a fix as mentioned here:  https://stackoverflow.com/questions/39171467/there-is-no-argument-provided-for-parameter-color-output-with-boost-test-and-cte

Did not work.  Unable to run the test suite.

This is using the latest master branch.

**Comment by riordant** [comment]
Tests have to be run on a Linux system.

**Comment by azilber** [comment]
Any plans on fixing that issue? :P

**Comment by ultimaweapon** [comment]
I have no idea why it does not work on other platforms. If it can compile `test_bitcoin` for that platform it should be able to run.

**Comment by qashban4** [comment]
For a developer using Mac OS, check it up.
