### ISSUE TITLE
Add more unit tests

### ISSUE THREAD

**Issue by thebevrishot** [firoorg/firo#621]
### double spend

- [ ] same serial in a single transaction.
- [ ] same serial in different transactions in same the same block.
- [ ] same serial in different blocks.
- [ ] success to add a serial twice (by delete the serial before add) and try to rebuild state the second transaction should not be added.
- [ ] spend two mints which have same commitment in difference denomination should success.

### invalid spend

- [ ] transaction with at least one proof which use invalid anonymity set should be rejected (index which is added to payload and real index are different).
- [ ] transaction with at least one empty proof should be rejected.
- [ ] try to spend a non-exists coin should be rejected.
- [ ] spend mint by specify difference denomination id, should be rejected.
- [ ] spend two coins which have same commitment in difference group should be rejected.
- [ ] spend by specify invalid group id, should be rejected.

### minting

- [ ] try to mint exceed balance should be rejected.

**Comment by ultimaweapon** [comment]
This one don't need to include in the sigma release to I will remove it from milestone.

**Comment by reubenyap** [comment]
@sproxet do your unit tests cover these?

**Comment by sproxet** [comment]
@reubenyap Most of them. Let me go through them one by one and add the ones that are missing...
