### ISSUE TITLE
Extensions supports

### ISSUE THREAD

**Issue by ultimaweapon** [firoorg/firo#682]
The idea is making Zcoin to be able to dynamically load shared libraries (`.so` on Linux, `.dylib` on macOS and `.dll` on Windows). Then Zcoin will call appropriate functions in that library whenever there is an event occurred (e.g. call `tip_connected` when a new tip has been connected). This will allow third party to easily working on Zcoin blockchain.

The path to a library will be configured by command line options or configuration entry (e.g. `-extension=C:\zcoin\foo.dll -extension=C:\zcoin\bar.dll`).

**Comment by psolstice** [comment]
Unfortunately it's an attack vector. Someone can publish the "extension" claiming it's doing something useful and use it to steal the secret keys. There is no one to sandbox the `.so` code. I bet it'll be used that way more often.

**Comment by ultimaweapon** [comment]
We can refuse to load if wallet is unencrypted.

**Comment by qashban4** [comment]
Future enhancement, could be 1 week work.
