### ISSUE TITLE
Make whole fix for wallet.py regtest. Now it is fixed till function call getFee

### ISSUE THREAD

**Issue by ultimaweapon** [firoorg/firo#711]
This is the issue migrated from Trello reported by Mariia. Not sure what it is. Need to take a look at `wallet.py` to see what wrong with it.

**Comment by qashban4** [comment]
Assign it to someone with Python experience.

**Comment by thebevrishot** [comment]
After take a look the file `wallet.py`, it contains a lot of comment out lines. I think this card mean we gonna fix commented tests.
