### ISSUE TITLE
Tweak LGTM configuration to get more useful analysis

### ISSUE THREAD

**Issue by qashban4** [firoorg/firo#733]
Tweak LGTM configuration to get more useful analysis.

For issues reported by current configurations you can see it here:
https://lgtm.com/projects/g/zcoinofficial/zcoin?mode=list

**Comment by ultimaweapon** [comment]
This is not a build system, it just code analysis. So I will remove that label.

**Comment by qashban4** [comment]
Could be half day work to complete this issue.
