### ISSUE TITLE
Design Specifications

### ISSUE THREAD

**Issue by ultimaweapon** [firoorg/firo#746]
- Each property will have it own configurations to have transfer fee or not.
- Fee will be paid with that property.
- Fee will paid to address configured for each property.

**Comment by thebevrishot** [comment]
To protect user I think we should have:
- `Max fee` for each property which token creator have to specify when create the token. We also should have system limit rate.
- After the fee changing transaction is mined we should wait some amount of confirmations to enforce it to let user be able to exit in case that the fee is raised excessively.
