### ISSUE TITLE
zcoin-cli getinfo hanging

### ISSUE THREAD

**Issue by clu8** [firoorg/firo#819]
## Actual behaviour
Running `./zcoin-cli getinfo` hangs indefinitely while zcoin is reindexing (OK for the first several 10k blocks). `ps -aux` indicates `./zcoind -daemon` is taking 99.1% CPU. Rebooting does not help. 

## Steps to reproduce
Ubuntu 18.04, Zcoin v0.13.8.10

Any troubleshooting steps? Thanks!!

**Comment by HysMagus** [comment]
Add debug=1 in your conf, restart the daemon, then attempt to replicate the point where it hangs, if you can post the excerpt of the log where the error occurs, that could help identify what's causing it to hang

**Comment by NorseGaud** [comment]
@HysMagus Is there an ENV for this? I'd like to not have to modify the conf to set debug to true.

**Comment by NorseGaud** [comment]
Also, I see: ```Error reading znode configuration file: Could not parse znode.conf
Line: 4
"debug=1"```

**Comment by justanwar** [comment]
Feel free to reopen if issue repeats itself.
