### ISSUE TITLE
[Debian] 0.13.8.10 does not accept password when starting MN

### ISSUE THREAD

**Issue by Newar417** [firoorg/firo#827]
## Actual behaviour
After updating to 0.13.8.10 when trying to start a MN, I get an error message that the password is wrong. Both password, local wallet- and MN setup are the same pretty much since Znodes started. I put a copy on a Win10 system and it works fine there. The password is in a password safe which serves both the Debian and the Win10, so typos are not the issue. 

## Desired behaviour
Recognise password is correct.

## Steps to reproduce
- Fully sync wallet, try to start MN
- Enter password

Distributor ID:	Debian
Description:	Devuan GNU/Linux 3 (beowulf)
Release:	3
Codename:	beowulf

I went on Discord and another user "Jeroz" chimed in, that he had the same problem, but he did not elaborate.

**Comment by reubenyap** [comment]
Reopen if still an issue.
