### ISSUE TITLE
Sync on Linux super slow

### ISSUE THREAD

**Issue by skironDotNet** [firoorg/firo#873]
Ubuntu Server 20.04 LTS
zcoin v0.14.0.2

Sync is super slow, I had a node on windows and linux with same height due to old version 13.8, on windows it synced in a few minutes, on linux it's been an hour and synced like 200 blocks.

CPU utilization 95-100% on 2 cores, the VPS is 6 core with 6GB ram. 
zcoin 6 connections to network.

Please check if relevant to this https://github.com/skironDotNet/DigitalNote-2/commit/411e0275ae10137b3745bd473b27ddb410e6981d

**Comment by skironDotNet** [comment]
The good news is that finally got synced 3000 blocks, and now CPU usage is close to 0 so only syncing seems to be a problem on Linux

**Comment by AExept** [comment]
Sync is slow on Arch Linux using the pre-built tarball also. Sync started around 80% per hour (that was about the expected speed on my network with a metered connection). Once I got to around halfway, the speed dropped down to about 1% per hour according to the output from zcoin-qt. There is no know environment issue that would have caused this. There were no hardware or software changes from the first half to the second half, and my monitors all reported far less resource usages than my capacity.

**Comment by NorseGaud** [comment]
What kind of disk are you using? Please provide the specs.

**Comment by skironDotNet** [comment]
Mine is on SSD, Linux IO is slower than disk capability, but measured under linux 250GB/s
