### ISSUE TITLE
cant compile zcoind in wsl

### ISSUE THREAD

**Issue by saymissme** [firoorg/firo#876]
step by step 
https://github.com/zcoinofficial/zcoin/blob/master/doc/build_windows_wsl.md

got this error

> ake[3]: Leaving directory '/root/coin/zcoin-0.14.0.2'
>  CXX      libbitcoin_server_a-bloom.o
>In file included from evo/providertx.h:8:0,
>                 from bloom.cpp:9:
>./bls/bls.h:322:18: error: ‘mutex’ in namespace ‘std’ does not name a type
>     mutable std::mutex mutex;
>                  ^~~~~
>./bls/bls.h: In member function ‘CBLSLazyWrapper<BLSObject>& CBLSLazyWrapper<BLSObject>::operator=(const >CBLSLazyWrapper<BLSObject>&)’:
>./bls/bls.h:347:31: error: ‘mutex’ is not a member of ‘std’
>         std::unique_lock<std::mutex> l(r.mutex);
>                               ^~~~~
>./bls/bls.h:347:31: note: suggested alternative: ‘quoted’
>         std::unique_lock<std::mutex> l(r.mutex);
>........
>Makefile:7590: recipe for target 'libbitcoin_server_a-bloom.o' failed
>make[2]: *** [libbitcoin_server_a-bloom.o] Error 1
>make[2]: Leaving directory '/root/coin/zcoin-0.14.0.2/src'
>Makefile:14303: recipe for target 'all-recursive' failed
>make[1]: *** [all-recursive] Error 1
>make[1]: Leaving directory '/root/coin/zcoin-0.14.0.2/src'
>Makefile:715: recipe for target 'all-recursive' failed
>make: *** [all-recursive] Error 1

how to fix it?
thx

**Comment by justanwar** [comment]
Which distro are using with wsl? What branch are you compiling? Are you trying to compile a Windows binary?

**Comment by saymissme** [comment]
yes
i want compile a Windows binary
use this code :
>https://github.com/zcoinofficial/zcoin/archive/v0.14.0.2.tar.gz

**Comment by psolstice** [comment]
the error is the result of not completing step 6 of the instruction (or doing it incorrectly)
