### ISSUE TITLE
Trezor does not show the transactions correctly

### ISSUE THREAD

**Issue by hakonamatata** [firoorg/firo#885]
### Describe the issue
Received transactions for my zcoin master node, but trezor does not show the transactions correctly

### Screenshots.

![image](https://user-images.githubusercontent.com/4003969/87714835-ada81e80-c7ac-11ea-89aa-285adf76ba5e.png)

**Comment by a-bezrukov** [comment]
This is the expected behavior for now. We are waiting for a new Trezor firmware which should add support for this. Now in order to spend your Znode outputs please use an Electrum-XZC BIP-39 wallet, created with your Trezor seed words (not an Electrum-XZC wallet, created with your Trezor device)

**Comment by hakonamatata** [comment]
> 
> 
> This is the expected behavior for now. We are waiting for a new Trezor firmware which should add support for this. Now in order to spend your Znode outputs please use an Electrum-XZC BIP-39 wallet, created with your Trezor seed words (not an Electrum-XZC wallet, created with your Trezor device)

Thanks for the info, I can wait until Trezor update their firmware. 

PS. When will trezor add support for zcoin (meaning you could select zcoin from a dropdown list, instead of specifying the url yourself). This must be an easy thing to add.

**Comment by a-bezrukov** [comment]
I'll investigate and PR this if they allow such PRs now.
