### ISSUE TITLE
Typos identified in the Lelantus paper

### ISSUE THREAD

**Issue by james-miller-93** [firoorg/firo#891]
## Description
Part of the Lelantus protocol involves providing range proofs, which prove that a particular commitment has a corresponding value within a certain range. The Lelantus protocol invokes a variant of Bulletproofs to achieve this for their double-blinded commitments.

When computing these range proofs, the prover computes bit-vectors **a_L** and **a_R**. As described in Appendix B of the Lelantus paper, **a_R** is defined to be **1** - **a_L**. However, the corresponding implementation in `range_prover.cpp` computes **a_R** as **a_L** - **1**:

```c++
std::vector<Scalar> aL, aR;
    aL.reserve(n * m);
    aR.reserve(n * m);
    for (std::size_t j = 0; j < m; ++j)
    {
        for (std::size_t i = 1; i <= n; ++i)
        {
            aL.emplace_back(uint64_t(bits[j][bits[j].size() - i]));
            aR.emplace_back(Scalar(uint64_t(bits[j][bits[j].size() - i])) - Scalar(uint64_t(1)));
        }
    }
```

This was identified as a typo in the paper.

In addition to this, there is another typo for computing the value `S` in the paper. Specifically, the paper should say S = (h1^p)(**g**^**s_L**)(**h**^**s_R**), but it says S = (h1^p)(**g**^**a_L**)(**h**^**a_R**).

**Comment by reubenyap** [comment]
The typo is noted and will be rectified in a future updated version.

**Comment by reubenyap** [comment]
Resolved https://eprint.iacr.org/2019/373
