### ISSUE TITLE
what  ./firod -migratetofiro do in release note?

### ISSUE THREAD

**Issue by lcgogo** [firoorg/firo#938]
i used to run zcoin by

zcoind -datadir=/data/zcoin

should I use migratetofiro?

Or I can do below steps instead?
stop zcoind
mv /data/zcoin/zcoin.conf /data/zcoin/firo.conf
mv /data/zcoin /data/firo
firod -datadir=/data/firo

**Comment by justanwar** [comment]
Since you are using a custom datadir, you will need to use the four steps that you posted.

**Comment by lcgogo** [comment]
> Since you are using a custom datadir, you will need to use the four steps that you posted.

Many thanks.
