### ISSUE TITLE
No zcoin.conf file to convert

### ISSUE THREAD

**Issue by roleerob** [firoorg/firo#970]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

### Describe the issue

In migrating from ZCOIN to FIRO, we were instructed to rename ZCOIN.CONF to FIRO.CONF.  In the directory I was using for ZCoin, there was no ZCOIN.CONF file.  Only a ZNODE.CONF file.

### Can you reliably reproduce the issue?

Yes

#### If so, please list the steps to reproduce below:
1.  I can run Firo Core without any FIRO.CONF file.
2.
3.

### Expected behaviour

Presumably the FIRO.CONF file is important, for proper execution of the Firo Core wallet.

### Actual behaviour

Firo Core opens and appears to be running fine without one, but I don't want to make a false assumption.  So ... I am writing this request for help.

### Screenshots.

Here is a dialog capture of what I saw, when first opening Firo Core:

![Firo_Migration_Issue](https://user-images.githubusercontent.com/31572169/104854534-69fdb100-58c4-11eb-84a9-7eb9143647c9.png)

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS: Windows 10 64-bit
- CPU: Intel i7-7700 HQ
- RAM: 32 GB
- Disk size: I TB
- Disk Type (HD/SDD): SDD

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by justanwar** [comment]
zcoin.conf is not mandatory for normal wallets and is not created as part of the installation process. You can safely proceed.
