### ISSUE TITLE
Wallet.dat File Corrupted - After Anonymization - MAC

### ISSUE THREAD

**Issue by dholliday5** [firoorg/firo#973]
MAC User - I anonymized my coins, and the wallet just shut down. I went to open it back up and it gave me the following error message "Error reading wallet.dat" All keys read correctly, but transaction data or address book entries might be missing or incorrect" screenshot below.
![image0](https://user-images.githubusercontent.com/46861810/104859776-8f56e300-58f5-11eb-8fd0-c999b870d02a.jpeg)

So I used one of my back up files, and the wallet opened , however I didn't see my anonymized coins. It does'nt show pending in the private balance either. However, I can see in the transaction history that they went out.

In addition, its creating the following file below in the firo folder: 
![Screen Shot 2021-01-17 at 7 19 16 PM](https://user-images.githubusercontent.com/46861810/104860344-08a40500-58f9-11eb-94ca-475ca07205f4.png)

**Comment by justanwar** [comment]
Do you have a backup of the wallet.dat after the Error? Please do not delete the wallet.*.bak file.

**Comment by dholliday5** [comment]
Yes, I do have a copy

**Comment by justanwar** [comment]
Wallet recovered and funds returned to user.
