### ISSUE TITLE
Is it possible to build firo on Raspberry Pi 4B 4GB running Raspberry Pi OS? __uint128_t not supported

### ISSUE THREAD

**Issue by blackmennewstyle** [firoorg/firo#980]
Hi,

My question is simple: Is it possible to build firo on Raspberry Pi 4B 4GB running Raspberry Pi OS?

I tried to follow the different instruction for [UNIX build ](https://github.com/firoorg/firo/blob/master/doc/build-unix.md) and also [ARM build](https://github.com/firoorg/firo/blob/master/depends/README.md) but i always run into the following issue:

```
In file included from /home/pi/firo-0.14.4.0/src/bls-signatures/contrib/relic/include/relic_arch.h:38,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/contrib/relic/include/relic_util.h:38,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/contrib/relic/include/relic_err.h:42,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/contrib/relic/include/relic_core.h:43,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/contrib/relic/src/relic_err.c:36:
/home/pi/firo-0.14.4.0/src/bls-signatures/contrib/relic/include/relic_types.h:112:9: error: unknown type name ‘__uint128_t’
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
make[5]: *** [contrib/relic/src/CMakeFiles/relic_s.dir/build.make:63: contrib/relic/src/CMakeFiles/relic_s.dir/relic_err.c.o] Error 1
make[5]: Leaving directory '/home/pi/firo-0.14.4.0/src/bls-signatures/build'
make[4]: *** [CMakeFiles/Makefile2:142: contrib/relic/src/CMakeFiles/relic_s.dir/all] Error 2
make[4]: *** Waiting for unfinished jobs....
[  2%] Building CXX object src/CMakeFiles/chiablstmp.dir/signature.cpp.o
In file included from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_arch.h:38,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic.h:86,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/chaincode.hpp:28,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/chaincode.cpp:15:
/home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_types.h:112:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
         __uint32_t
In file included from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_arch.h:38,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic.h:86,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/util.hpp:30,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/publickey.hpp:27,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/extendedpublickey.hpp:26,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/extendedpublickey.cpp:16:
/home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_types.h:112:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
         __uint32_t
In file included from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_arch.h:38,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic.h:86,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/util.hpp:30,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/publickey.hpp:27,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/privatekey.hpp:24,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/extendedprivatekey.hpp:26,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/extendedprivatekey.cpp:17:
/home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_types.h:112:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
         __uint32_t
make[5]: *** [src/CMakeFiles/chiablstmp.dir/build.make:63: src/CMakeFiles/chiablstmp.dir/extendedpublickey.cpp.o] Error 1
make[5]: *** Waiting for unfinished jobs....
make[5]: *** [src/CMakeFiles/chiablstmp.dir/build.make:76: src/CMakeFiles/chiablstmp.dir/extendedprivatekey.cpp.o] Error 1
make[5]: *** [src/CMakeFiles/chiablstmp.dir/build.make:89: src/CMakeFiles/chiablstmp.dir/chaincode.cpp.o] Error 1
In file included from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_arch.h:38,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic.h:86,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/util.hpp:30,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/signature.hpp:27,
                 from /home/pi/firo-0.14.4.0/src/bls-signatures/src/signature.cpp:20:
/home/pi/firo-0.14.4.0/src/bls-signatures/src/../contrib/relic/include/relic_types.h:112:9: error: ‘__uint128_t’ does not name a type; did you mean ‘__uint32_t’?
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
         __uint32_t
make[5]: *** [src/CMakeFiles/chiablstmp.dir/build.make:102: src/CMakeFiles/chiablstmp.dir/signature.cpp.o] Error 1
make[5]: Leaving directory '/home/pi/firo-0.14.4.0/src/bls-signatures/build'
make[4]: *** [CMakeFiles/Makefile2:200: src/CMakeFiles/chiablstmp.dir/all] Error 2
make[4]: Leaving directory '/home/pi/firo-0.14.4.0/src/bls-signatures/build'
make[3]: *** [Makefile:130: all] Error 2
make[3]: Leaving directory '/home/pi/firo-0.14.4.0/src/bls-signatures/build'
make[2]: *** [Makefile:5: build/libchiabls.a] Error 2
make[2]: Leaving directory '/home/pi/firo-0.14.4.0/src/bls-signatures'
make[1]: *** [Makefile:15812: all-recursive] Error 1
make[1]: Leaving directory '/home/pi/firo-0.14.4.0/src'
make: *** [Makefile:716: all-recursive] Error 1
```

**Comment by PanderMusubi** [comment]
Same error for firo-0.14.5.3 on Raspberry Pi OS Buster after

    sudo apt-get install autoconf libtool libdb++-dev libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-program-options-dev libboost-test-dev libboost-thread-dev libgmp-dev
    ./configure --with-incompatible-bd
    make -j

**Comment by PanderMusubi** [comment]
Also same result when using host triplet explicitly

    sudo apt-get install autoconf libtool libdb++-dev
    cd depends
    make -j NO_QT=1 HOST=arm-linux-gnueabihf
    cd ..
    ./autogen.sh
    ./configure --with-incompatible-bdb --prefix=`pwd`/depends/arm-linux-gnueabihf
    make -j

**Comment by PanderMusubi** [comment]
For Dash, it was fixed in this way https://github.com/dashpay/dash/pull/2601 (see also the related issue). So Firo needs this fix probably too.

**Comment by PanderMusubi** [comment]
Just additional info: Same error in Ubuntu Groove container on Turris Omnia which has dual core `armv7l` with 2 GB. Difference is that this has `g++-10` and Buster has `g++-8`. (Do not use `-j` on more limited systems.)

**Comment by fanaticalfishing** [comment]
Firo will build on a Raspberry pi Running a 64 bit Raspberry pi OS. It runs well on Ubuntu 20.04 LTS 64 bit
https://ubuntu.com/download/raspberry-pi
There is no bitcoin source for focal so change it to artful

https://pastbin.net/firo-on-raspberry-pi

**Comment by blackmennewstyle** [comment]
> Firo will build on a Raspberry pi Running a 64 bit Raspberry pi OS. It runs well on Ubuntu 20.04 LTS 64 bit https://ubuntu.com/download/raspberry-pi There is no bitcoin source for focal so change it to artful
> 
> https://pastbin.net/firo-on-raspberry-pi

Totally forgot about this thread. I indeed managed to install FIRO using [GNU/Linux Debian 10/11 with arm64 kernel](https://salsa.debian.org/raspi-team/image-specs) - Please be aware, this is not Raspberry Pi OS which uses a 32 bits arm kernel. Also if you want to install **Berkeley DB 4.8**, the OG Bitcoin provides a pretty fantastic script with patches which will build it for you. At the end of the process, the script will even provides you an example on how to force `./configure` with that custom build.
```
wget https://raw.githubusercontent.com/bitcoin/bitcoin/master/contrib/install_db4.sh
./install_db4.sh `pwd`
```

**Comment by fanaticalfishing** [comment]
Thanks. I have electrumx-firo runnning with help from justanwar. It uses leveldb
Privacy should be improved by connecting to my own server

**Comment by justanwar** [comment]
The build instructions in `master` has been updated with a new way to build Firo and should not require workarounds anymore for arm64.

I have tested it with Raspberry Pi OS Bullseye and Ubuntu 21.10. Please give it a try on your Pis, and feel free to reopen this issue if the problem persists.

**Comment by PanderMusubi** [comment]
Please see https://github.com/firoorg/firo/issues/1100#issuecomment-1124662883 for where build process on RPi is stuck at the moment (perhaps this deserves a new issue?)

**Comment by fanaticalfishing** [comment]
> Please see [#1100 (comment)](https://github.com/firoorg/firo/issues/1100#issuecomment-1124662883) for where build process on RPi is stuck at the moment (perhaps this deserves a new issue?)

when i tried to build it on pi some time ago it got stuck because it ran out of memory. I added more swap space and it worked. But Firo has pre compiled binaries for the Pi available now.
